(function(g){var window=this;var wIa=function(a,b){return g.Mb(a,b)},M4=function(a,b,c){a.l.set(b,c)},N4=function(a){M4(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Sa()).toString(36));
return a},O4=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.cn(a.l,b,c)},xIa=function(a,b){var c=[];
g.mj(b,function(d){try{var e=g.Qn.prototype.l.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Pn(e)&&c.push(d)},a);
return c},yIa=function(a,b){var c=xIa(a,b);
g.Ab(c,function(d){g.Qn.prototype.remove.call(this,d)},a)},zIa=function(a){if(a.W){if(a.W.locationOverrideToken)return{locationOverrideToken:a.W.locationOverrideToken};
if(null!=a.W.latitudeE7&&null!=a.W.longitudeE7)return{latitudeE7:a.W.latitudeE7,longitudeE7:a.W.longitudeE7}}return null},AIa=function(a,b){g.fb(a,b)||a.push(b)},P4=function(a){var b=0,c;
for(c in a)b++;return b},BIa=function(a,b){var c=b instanceof g.Gc?b:g.Mc(b,/^data:image\//i.test(b));
a.src=g.Hc(c)},Q4=function(){},CIa=function(a){try{return g.A.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},DIa=function(a){if(a.tg&&"function"==typeof a.tg)return a.tg();
if("string"===typeof a)return a.split("");if(g.Ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Jb(a)},EIa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ma(a)||"string"===typeof a)g.Ab(a,b,void 0);else{if(a.qh&&"function"==typeof a.qh)var c=a.qh();else if(a.tg&&"function"==typeof a.tg)c=void 0;else if(g.Ma(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Kb(a);d=DIa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},FIa=function(a,b,c,d){var e=new g.Rm(null,void 0);
a&&g.Sm(e,a);b&&g.Tm(e,b);c&&g.Um(e,c);d&&(e.J=d);return e},R4=function(a,b){g.Fo[a]=!0;
var c=g.Do();c&&c.publish.apply(c,arguments);g.Fo[a]=!1},S4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Om;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",GIa(this,a.capabilities||""),HIa(this,a.experiments||""))},GIa=function(a,b){a.capabilities.clear();
g.Ne(b.split(","),g.Qa(wIa,IIa)).forEach(function(c){a.capabilities.add(c)})},HIa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},T4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},U4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},JIa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},KIa=function(a){return new T4(a)},LIa=function(a){return Array.isArray(a)?g.Qc(a,KIa):[]},V4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},W4=function(a){return Array.isArray(a)?"["+g.Qc(a,V4).join(",")+"]":"null"},X4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},MIa=function(a){return g.Qc(a,function(b){return{key:b.id,
name:b.name}})},Y4=function(a,b){return g.cb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},Z4=function(a,b){return g.cb(a,function(c){return U4(c,b)})},NIa=function(){var a=(0,g.Hu)();
a&&yIa(a,a.i.Rj(!0))},$4=function(){var a=g.Ku("yt-remote-connected-devices")||[];
g.xb(a);return a},OIa=function(a){if(g.gb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Qc(a,function(d,e){return 0==e?d:d.substring(c.length)})},PIa=function(a){g.Ju("yt-remote-connected-devices",a,86400)},b5=function(){if(a5)return a5;
var a=g.Ku("yt-remote-device-id");a||(a=X4(),g.Ju("yt-remote-device-id",a,31536E3));for(var b=$4(),c=1,d=a;g.fb(b,d);)c++,d=a+"#"+c;return a5=d},c5=function(){var a=$4(),b=b5();
g.fb(a,b);g.Mu()&&g.zb(a,b);a=OIa(a);if(g.gb(a))try{g.Wq("remote_sid")}catch(c){}else try{g.Uq("remote_sid",a.join(","),-1)}catch(c){}},QIa=function(){return g.Ku("yt-remote-session-browser-channel")},RIa=function(){return g.Ku("yt-remote-local-screens")||[]},SIa=function(){g.Ju("yt-remote-lounge-token-expiration",!0,86400)},TIa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Qc(RIa(),function(d){return d.loungeToken}),c=g.Qc(a,function(d){return d.loungeToken});
g.qh(c,function(d){return!g.fb(b,d)})&&SIa();
g.Ju("yt-remote-local-screens",a,31536E3)},UIa=function(a,b){g.Ju("yt-remote-session-browser-channel",a);
g.Ju("yt-remote-session-screen-id",b);var c=$4(),d=b5();g.fb(c,d)||c.push(d);PIa(c);c5()},d5=function(a){a||(g.Lu("yt-remote-session-screen-id"),g.Lu("yt-remote-session-video-id"));
c5();a=$4();g.kb(a,b5());PIa(a)},VIa=function(){if(!e5){var a=g.ho();
a&&(e5=new g.Kn(a))}},WIa=function(){VIa();
return e5?!!e5.get("yt-remote-use-staging-server"):!1},f5=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},XIa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},YIa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},g5=function(a){a.length?ZIa(a.shift(),function(){g5(a)}):h5()},$Ia=function(a){return"chrome-extension://"+a+"/cast_sender.js"},ZIa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.nd(d,g.qg(a));(document.head||document.documentElement).appendChild(d)},aJa=function(){var a=f5(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},h5=function(){var a=YIa();
a&&a(!1,"No cast extension found")},i5=function(){if(bJa){var a=2,b=YIa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;ZIa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",h5,c)}},cJa=function(){i5();
var a=aJa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");g5(a)},eJa=function(){i5();
var a=aJa();a.push.apply(a,g.la(dJa.map($Ia)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");g5(a)},j5=function(a,b,c){g.E.call(this);
this.I=null!=c?(0,g.B)(a,c):a;this.Kf=b;this.C=(0,g.B)(this.LJ,this);this.i=!1;this.l=0;this.u=this.ib=null;this.B=[]},k5=function(a,b,c){g.E.call(this);
this.B=null!=c?a.bind(c):a;this.Kf=b;this.u=null;this.i=!1;this.l=0;this.ib=null},l5=function(a){a.ib=g.Mm(function(){a.ib=null;
a.i&&!a.l&&(a.i=!1,l5(a))},a.Kf);
var b=a.u;a.u=null;a.B.apply(null,b)},m5=function(a){if(g.A.JSON)try{return g.A.JSON.parse(a)}catch(b){}return CIa(a)},n5=function(){},o5=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.A.setTimeout(function(){a()},b)},q5=function(a){p5.dispatchEvent(new fJa(p5,a))},fJa=function(a,b){g.Il.call(this,"statevent",a);
this.stat=b},r5=function(){},gJa=function(){},iJa=function(a){return(a=hJa(a))?new ActiveXObject(a):new XMLHttpRequest},hJa=function(a){if(!a.l&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.l=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.l},s5=function(a,b,c,d){this.i=a;
this.l=b;this.L=c;this.J=d||1;this.C=45E3;this.B=new g.M_(this);this.u=new g.Lm;this.u.setInterval(250)},kJa=function(a,b,c){a.Ep=1;
a.Tk=N4(b.clone());a.Fn=c;a.I=!0;jJa(a,null)},t5=function(a,b,c,d,e){a.Ep=1;
a.Tk=N4(b.clone());a.Fn=null;a.I=c;e&&(a.KG=!1);jJa(a,d)},jJa=function(a,b){a.tp=g.Sa();
u5(a);a.Sl=a.Tk.clone();O4(a.Sl,"t",a.J);a.Es=0;a.Ee=a.i.Ax(a.i.ds()?b:null);0<a.xw&&(a.Su=new k5((0,g.B)(a.HH,a,a.Ee),a.xw));a.B.za(a.Ee,"readystatechange",a.ZP);var c=a.km?g.Vb(a.km):{};a.Fn?(a.Fv="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Ee.send(a.Sl,a.Fv,a.Fn,c)):(a.Fv="GET",a.KG&&!g.De&&(c.Connection="close"),a.Ee.send(a.Sl,a.Fv,null,c));a.i.ii(1)},nJa=function(a,b,c){for(var d=!0;!a.Nm&&a.Es<c.length;){var e=lJa(a,c);
if(e==v5){4==b&&(a.Nk=4,q5(15),d=!1);break}else if(e==mJa){a.Nk=4;q5(16);d=!1;break}else w5(a,e)}4==b&&0==c.length&&(a.Nk=1,q5(17),d=!1);a.yi=a.yi&&d;d||(x5(a),y5(a))},lJa=function(a,b){var c=a.Es,d=b.indexOf("\n",c);
if(-1==d)return v5;c=Number(b.substring(c,d));if(isNaN(c))return mJa;d+=1;if(d+c>b.length)return v5;var e=b.substr(d,c);a.Es=d+c;return e},pJa=function(a,b){a.tp=g.Sa();
u5(a);var c=b?window.location.hostname:"";a.Sl=a.Tk.clone();M4(a.Sl,"DOMAIN",c);M4(a.Sl,"t",a.J);try{a.Ci=new ActiveXObject("htmlfile")}catch(n){x5(a);a.Nk=7;q5(22);y5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)h=e+"\\x3c";else if(">"==h)h=e+"\\x3e";else{if(h in z5)h=z5[h];else if(h in oJa)h=z5[h]=oJa[h];else{var l=h.charCodeAt(0);if(31<l&&127>l)var m=h;else{if(256>l){if(m="\\x",16>l||256<l)m+="0"}else m="\\u",4096>l&&(m+="0");m+=l.toString(16).toUpperCase()}h=
z5[h]=m}h=e+h}e=h}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.kd(g.gc("b/12014412"),d+"</body></html>");a.Ci.open();a.Ci.write(g.gd(c));a.Ci.close();a.Ci.parentWindow.m=(0,g.B)(a.vP,a);a.Ci.parentWindow.d=(0,g.B)(a.VF,a,!0);a.Ci.parentWindow.rpcClose=(0,g.B)(a.VF,a,!1);c=a.Ci.createElement("DIV");a.Ci.parentWindow.document.body.appendChild(c);d=g.Lc(a.Sl.toString());d=g.sd(g.Hc(d));d=g.kd(g.gc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.ld(c,d);a.i.ii(1)},u5=function(a){a.KA=g.Sa()+
a.C;
qJa(a,a.C)},qJa=function(a,b){if(null!=a.Kp)throw Error("WatchDog timer not null");
a.Kp=o5((0,g.B)(a.DP,a),b)},A5=function(a){a.Kp&&(g.A.clearTimeout(a.Kp),a.Kp=null)},y5=function(a){a.i.IB()||a.Nm||a.i.Vs(a)},x5=function(a){A5(a);
g.Pi(a.Su);a.Su=null;a.u.stop();g.RCa(a.B);if(a.Ee){var b=a.Ee;a.Ee=null;b.abort();b.dispose()}a.Ci&&(a.Ci=null)},w5=function(a,b){try{a.i.MF(a,b),a.i.ii(4)}catch(c){}},sJa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;rJa(a,b,function(h){h?c(!0):g.A.setTimeout(function(){sJa(a,b,c,d,f)},f)})}},rJa=function(a,b,c){var d=new Image;
d.onload=function(){try{B5(d),c(!0)}catch(e){}};
d.onerror=function(){try{B5(d),c(!1)}catch(e){}};
d.onabort=function(){try{B5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{B5(d),c(!1)}catch(e){}};
g.A.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
BIa(d,a)},B5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},C5=function(a){g.bm.call(this);
this.headers=new g.Om;this.ea=a||null;this.B=!1;this.ca=this.i=null;this.Aa=this.W="";this.I=0;this.u="";this.C=this.la=this.L=this.ga=!1;this.J=0;this.X=null;this.Ca="";this.Y=this.ia=!1},tJa=function(a){return g.Be&&g.ce(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},uJa=function(a){return"content-type"==a.toLowerCase()},wJa=function(a,b){a.B=!1;
a.i&&(a.C=!0,a.i.abort(),a.C=!1);a.u=b;a.I=5;vJa(a);D5(a)},vJa=function(a){a.ga||(a.ga=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},yJa=function(a){if(a.B&&"undefined"!=typeof g.P_)if(a.ca[1]&&4==E5(a)&&2==a.getStatus())F5(a,"Local request error detected and ignored");
else if(a.L&&4==E5(a))g.Mm(a.JF,0,a);else if(a.dispatchEvent("readystatechange"),a.isComplete()){F5(a,"Request complete");a.B=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Bd(1,String(a.W));if(!f&&g.A.self&&g.A.self.location){var h=g.A.self.location.protocol;f=h.substr(0,h.length-1)}e=!xJa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.I=6;try{var l=2<E5(a)?a.i.statusText:""}catch(m){l=""}a.u=l+" ["+a.getStatus()+"]";vJa(a)}}finally{D5(a)}}},D5=function(a,b){if(a.i){zJa(a);
var c=a.i,d=a.ca[0]?g.Ia:null;a.i=null;a.ca=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},zJa=function(a){a.i&&a.Y&&(a.i.ontimeout=null);
a.X&&(g.A.clearTimeout(a.X),a.X=null)},E5=function(a){return a.i?a.i.readyState:0},G5=function(a){try{return a.i?a.i.responseText:""}catch(b){return""}},F5=function(a,b){return b+" ["+a.Aa+" "+a.W+" "+a.getStatus()+"]"},AJa=function(a){this.i=a;
this.l=new n5},BJa=function(a){var b=H5(a.i,a.mq,"/mail/images/cleardot.gif");
N4(b);sJa(b.toString(),5E3,(0,g.B)(a.CK,a),3,2E3);a.ii(1)},J5=function(a){var b=a.i.L;
if(null!=b)q5(5),b?(q5(11),I5(a.i,a,!1)):(q5(12),I5(a.i,a,!0));else if(a.Cg=new s5(a,void 0,void 0,void 0),a.Cg.km=a.yw,b=a.i,b=H5(b,b.ds()?a.cq:null,a.zw),q5(5),!g.Be||g.de(10))O4(b,"TYPE","xmlhttp"),t5(a.Cg,b,!1,a.cq,!1);else{O4(b,"TYPE","html");var c=a.Cg;a=!!a.cq;c.Ep=3;c.Tk=N4(b.clone());pJa(c,a)}},K5=function(a,b,c){this.Ma=1;
this.i=[];this.u=[];this.B=new n5;this.J=a||null;this.L=null!=b?b:null;this.C=c||!1},CJa=function(a,b){this.i=a;
this.map=b;this.context=null},DJa=function(a,b,c,d){g.Il.call(this,"timingevent",a);
this.size=b;this.Tr=d},EJa=function(a){g.Il.call(this,"serverreachability",a)},HJa=function(a){FJa(a);
if(3==a.Ma){var b=a.Ar++,c=a.Bt.clone();M4(c,"SID",a.l);M4(c,"RID",b);M4(c,"TYPE","terminate");L5(a,c);b=new s5(a,a.l,b,void 0);b.Ep=2;b.Tk=N4(c.clone());BIa(new Image,b.Tk.toString());b.tp=g.Sa();u5(b)}GJa(a)},IJa=function(a){a.WK(1,0);
a.Bt=H5(a,null,a.Aw);M5(a)},FJa=function(a){a.Xk&&(a.Xk.abort(),a.Xk=null);
a.Zd&&(a.Zd.cancel(),a.Zd=null);a.Sj&&(g.A.clearTimeout(a.Sj),a.Sj=null);N5(a);a.qg&&(a.qg.cancel(),a.qg=null);a.kl&&(g.A.clearTimeout(a.kl),a.kl=null)},JJa=function(a,b){if(0==a.Ma)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new CJa(a.uM++,b));2!=a.Ma&&3!=a.Ma||M5(a)},KJa=function(a){var b=0;
a.Zd&&b++;a.qg&&b++;return b},M5=function(a){a.qg||a.kl||(a.kl=o5((0,g.B)(a.TF,a),0),a.Bo=0)},MJa=function(a,b){if(1==a.Ma){if(!b){a.Ar=Math.floor(1E5*Math.random());
var c=a.Ar++,d=new s5(a,"",c,void 0);d.km=a.Ii;var e=O5(a),f=a.Bt.clone();M4(f,"RID",c);M4(f,"CVER","1");L5(a,f);kJa(d,f,e);a.qg=d;a.Ma=2}}else 3==a.Ma&&(b?LJa(a,b):0==a.i.length||a.qg||LJa(a))},LJa=function(a,b){if(b)if(6<a.Om){a.i=a.u.concat(a.i);
a.u.length=0;var c=a.Ar-1;var d=O5(a)}else c=b.L,d=b.Fn;else c=a.Ar++,d=O5(a);var e=a.Bt.clone();M4(e,"SID",a.l);M4(e,"RID",c);M4(e,"AID",a.Uo);L5(a,e);c=new s5(a,a.l,c,a.Bo+1);c.km=a.Ii;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.qg=c;kJa(c,e,d)},L5=function(a,b){if(a.Cf){var c=a.Cf.tD();
c&&g.Cb(c,function(d,e){M4(b,e,d)})}},O5=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Om&&0<b){var d=a.i[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={Wn:e.Wn},f++){e.Wn=a.i[f].i;var h=a.i[f].map;e.Wn=6>=a.Om?f:e.Wn-d;try{g.Cb(h,function(l){return function(m,n){c.push("req"+l.Wn+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.Wn+"_type="+encodeURIComponent("_badmap"))}}a.u=a.u.concat(a.i.splice(0,b));
return c.join("&")},NJa=function(a){a.Zd||a.Sj||(a.I=1,a.Sj=o5((0,g.B)(a.SF,a),0),a.lo=0)},P5=function(a){if(a.Zd||a.Sj||3<=a.lo)return!1;
a.I++;a.Sj=o5((0,g.B)(a.SF,a),OJa(a,a.lo));a.lo++;return!0},I5=function(a,b,c){a.Dv=c;
a.Ji=b.Pj;a.C||IJa(a)},N5=function(a){null!=a.Wm&&(g.A.clearTimeout(a.Wm),a.Wm=null)},OJa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},Q5=function(a,b){if(2==b||9==b){var c=null;
a.Cf&&(c=null);var d=(0,g.B)(a.HQ,a);c||(c=new g.Rm("//www.google.com/images/cleardot.gif"),N4(c));rJa(c.toString(),1E4,d)}else q5(2);PJa(a,b)},PJa=function(a,b){a.Ma=0;
a.Cf&&a.Cf.JC(b);GJa(a);FJa(a)},GJa=function(a){a.Ma=0;
a.Ji=-1;if(a.Cf)if(0==a.u.length&&0==a.i.length)a.Cf.jx();else{g.ob(a.u);var b=g.ob(a.i);a.u.length=0;a.i.length=0;a.Cf.jx(b)}},H5=function(a,b,c){var d=g.Zm(c);
if(""!=d.i)b&&g.Tm(d,b+"."+d.i),g.Um(d,d.u);else{var e=window.location;d=FIa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Gq&&g.Cb(a.Gq,function(f,h){M4(d,h,f)});
M4(d,"VER",a.Om);L5(a,d);return d},QJa=function(){},RJa=function(){this.i=[];
this.l=[]},SJa=function(a,b){this.action=a;
this.params=b||{}},R5=function(a,b){g.E.call(this);
this.i=new g.M(this.nP,0,this);g.I(this,this.i);this.Kf=5E3;this.l=0;if("function"===typeof a)b&&(a=(0,g.B)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.B)(a.handleEvent,a);else throw Error("Invalid listener argument");this.u=a},S5=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.ca=a;this.I=b;this.u=new g.Jn;this.l=new R5(this.jQ,this);this.i=null;this.X=!1;this.C=null;this.W="";this.L=this.B=0;this.J=[];this.ea=c;this.Y=d;this.ia=e},TJa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.Dv,sessionId:a.i.l,arrayId:a.i.Uo}},UJa=function(a,b){a.L=b||0;
a.l.stop();T5(a);a.i&&(3==a.i.getState()&&MJa(a.i),HJa(a.i));a.L=0},U5=function(a){return!!a.i&&3==a.i.getState()},T5=function(a){if(a.i){var b=a.Y(),c=a.i.Ii||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.Ii=c}},V5=function(a){this.scheme="https";
this.port=this.domain="";this.i="/api/lounge";this.l=!0;a=a||document.location.href;var b=Number(g.Bd(4,a))||"";b&&(this.port=":"+b);this.domain=g.Cd(a)||"";a=g.Wc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ec(a,"10.0")&&(this.l=!1))},W5=function(a,b){var c=a.i;
a.l&&(c=a.scheme+"://"+a.domain+a.port+a.i);return g.Od(c+b,{})},X5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.B,d,!0),onError:g.Qa(a.u,e),onTimeout:g.Qa(a.C,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Zp(b,a)},YJa=function(){var a=VJa;
WJa();Y5.push(a);XJa()},Z5=function(a,b){WJa();
var c=ZJa(a,String(b));g.gb(Y5)?$Ja(c):(XJa(),g.Ab(Y5,function(d){d(c)}))},WJa=function(){Y5||(Y5=g.Ha("yt.mdx.remote.debug.handlers_")||[],g.Da("yt.mdx.remote.debug.handlers_",Y5,void 0))},$Ja=function(a){var b=($5+1)%50;
$5=b;a6[b]=a;b6||(b6=49==b)},XJa=function(){var a=Y5;
if(a6[0]){var b=b6?$5:-1;do{b=(b+1)%50;var c=a6[b];g.Ab(a,function(d){d(c)})}while(b!=$5);
a6=Array(50);$5=-1;b6=!1}},ZJa=function(a,b){var c=(g.Sa()-aKa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},c6=function(a){g.R.call(this);
this.I=a;this.screens=[]},bKa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},cKa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Ne(a.screens,function(f){return!!Y4(b,f)});
for(var d=0,e=b.length;d<e;d++)c=bKa(a,b[d])||c;return c},dKa=function(a,b){var c=a.screens.length;
a.screens=g.Ne(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},d6=function(a,b,c,d,e){g.R.call(this);
this.u=a;this.J=b;this.B=c;this.I=d;this.C=e;this.l=0;this.i=null;this.ib=NaN},f6=function(a){c6.call(this,"LocalScreenService");
this.l=a;this.i=NaN;e6(this);this.info("Initializing with "+W4(this.screens))},eKa=function(a){if(a.screens.length){var b=g.Qc(a.screens,function(d){return d.id}),c=W5(a.l,"/pairing/get_lounge_token_batch");
X5(a.l,c,{screen_ids:b.join(",")},(0,g.B)(a.xL,a),(0,g.B)(a.wL,a))}},e6=function(a){if(g.Qo("deprecate_pair_servlet_enabled"))return cKa(a,[]);
var b=LIa(RIa());b=g.Ne(b,function(c){return!c.uuid});
return cKa(a,b)},g6=function(a,b){TIa(g.Qc(a.screens,JIa));
b&&SIa()},i6=function(a,b){g.R.call(this);
this.I=b;var c=g.Ku("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.I(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.fb(c,l)}this.i=d;this.C=a;this.u=this.B=NaN;this.l=null;h6("Initialized with "+g.Qj(this.i))},j6=function(a,b,c){var d=W5(a.C,"/pairing/get_screen_availability");
X5(a.C,d,{lounge_token:b.token},(0,g.B)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.B)(function(){c(!1)},a))},k6=function(a,b){a:if(P4(b)!=P4(a.i))var c=!1;
else{c=g.Kb(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(h6("Updated online screens: "+g.Qj(a.i)),a.i=b,a.V("screenChange"));fKa(a)},l6=function(a){isNaN(a.u)||g.Co(a.u);
a.u=g.Ao((0,g.B)(a.Lz,a),0<a.B&&a.B<g.Sa()?2E4:1E4)},h6=function(a){Z5("OnlineScreenService",a)},gKa=function(a){var b={};
g.Ab(a.I(),function(c){c.token?b[c.token]=c.id:this.Id("Requesting availability of screen w/o lounge token.")});
return b},fKa=function(a){a=g.Kb(g.Db(a.i,function(b){return b}));
g.xb(a);a.length?g.Ju("yt-remote-online-screen-ids",a.join(","),60):g.Lu("yt-remote-online-screen-ids")},m6=function(a){c6.call(this,"ScreenService");
this.B=a;this.i=this.l=null;this.u=[];this.C={};hKa(this)},jKa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.C[b]);var h=a.Ng();if(h=(c?Z4(h,c):null)||Z4(h,b)){h.uuid=b;var l=n6(a,h);j6(a.i,l,function(m){e(m?l:null)})}else c?iKa(a,c,(0,g.B)(function(m){var n=n6(this,new T4({name:d,
screenId:c,loungeToken:m,dialId:b||""}));j6(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},kKa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},lKa=function(a,b,c){j6(a.i,b,c)},iKa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Zp(W5(a.B,"/pairing/get_lounge_token_batch"),e)},mKa=function(a){a.screens=a.l.Ng();
var b=a.C,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+W4(a.screens))},hKa=function(a){o6(a);
a.l=new f6(a.B);a.l.subscribe("screenChange",(0,g.B)(a.DL,a));mKa(a);a.u=LIa(g.Ku("yt-remote-automatic-screen-cache")||[]);o6(a);a.info("Initializing automatic screens: "+W4(a.u));a.i=new i6(a.B,(0,g.B)(a.Ng,a,!0));a.i.subscribe("screenChange",(0,g.B)(function(){this.V("onlineScreenChange")},a))},n6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=Z4(a.u,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.u.push(b),nKa(a));o6(a);a.C[b.uuid]=b.id;g.Ju("yt-remote-device-id-map",a.C,31536E3);return b},nKa=function(a){a=g.Ne(a.u,function(b){return"shortLived"!=b.idType});
g.Ju("yt-remote-automatic-screen-cache",g.Qc(a,JIa))},o6=function(a){a.C=g.Ku("yt-remote-device-id-map")||{}},p6=function(a,b,c){g.R.call(this);
this.ia=c;this.u=a;this.i=b;this.B=null},q6=function(a,b){a.B=b;
a.V("sessionScreen",a.B)},oKa=function(a,b){a.B&&(a.B.token=b,n6(a.u,a.B));
a.V("sessionScreen",a.B)},r6=function(a,b){Z5(a.ia,b)},s6=function(a,b,c){p6.call(this,a,b,"CastSession");
var d=this;this.ga=c;this.l=null;this.Y=(0,g.B)(this.QJ,this);this.ea=(0,g.B)(this.HP,this);this.X=g.Ao(function(){pKa(d,null)},12E4);
this.J=this.C=this.I=this.L=0;this.ca=!1;this.W="unknown"},t6=function(a,b){g.Co(a.J);
a.J=0;0==b?qKa(a):a.J=g.Ao(function(){qKa(a)},b)},qKa=function(a){rKa(a,"getLoungeToken");
g.Co(a.C);a.C=g.Ao(function(){sKa(a,null)},3E4)},rKa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Qj(void 0));
var c={};c.type=b;a.l?a.l.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ia,(0,g.B)(function(){r6(this,"Failed to send message: "+b+".")},a)):r6(a,"Sending yt message without session: "+g.Qj(c))},u6=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.KD(b,function(c){q6(a,c)},function(){return a.dg()},5)):a.dg(Error("Waiting for session status timed out."))},uKa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new T4(b);tKa(a,d,function(e){e?(a.ca=!0,n6(a.u,d),q6(a,d),a.W="unknown",t6(a,c)):(g.xo(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.dg())},5)},pKa=function(a,b){g.Co(a.X);
a.X=0;b?a.ga.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?uKa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.xo(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),u6(a,b.screenId))):(g.xo(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),
u6(a,b.screenId)):u6(a,b.screenId):a.dg(Error("Waiting for session status timed out."))},sKa=function(a,b){g.Co(a.C);
a.C=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.W=c,t6(a,3E4)):(oKa(a,b.loungeToken),a.ca=!1,a.W="unknown",t6(a,b.loungeTokenRefreshIntervalMs))},tKa=function(a,b,c,d){g.Co(a.I);
a.I=0;lKa(a.u,b,function(e){e||0>d?c(e):a.I=g.Ao(function(){tKa(a,b,c,d-1)},300)})},vKa=function(a){g.Co(a.L);
a.L=0;g.Co(a.I);a.I=0;g.Co(a.X);a.X=0;g.Co(a.C);a.C=0;g.Co(a.J);a.J=0},v6=function(a,b,c,d){p6.call(this,a,b,"DialSession");
this.ma=d;this.l=this.L=null;this.ea="";this.Aa=c;this.la=null;this.X=g.Ia;this.W=NaN;this.ga=(0,g.B)(this.RJ,this);this.C=g.Ia;this.J=this.I=0;this.Y=!1;this.ca="unknown"},w6=function(a){var b;
return!!(a.ma.enableDialLoungeToken&&(null==(b=a.l)?0:b.getDialAppInfo))},wKa=function(a){a.C=a.u.KB(a.ea,a.i.label,a.i.friendlyName,w6(a),function(b,c){a.C=g.Ia;
a.Y=!0;q6(a,b);"shortLived"==b.idType&&0<c&&x6(a,c)},function(b){a.C=g.Ia;
a.dg(b)})},xKa=function(a){var b={};
b.pairingCode=a.ea;b.theme=a.Aa;WIa()&&(b.env_useStageMdx=1);return g.Md(b)},y6=function(a){return new Promise(function(b){a.ea=X4();
if(a.la){var c=new chrome.cast.DialLaunchResponse(!0,xKa(a));b(c);wKa(a)}else a.X=function(){g.Co(a.W);a.X=function(){};
a.W=NaN;var d=new chrome.cast.DialLaunchResponse(!0,xKa(a));b(d);wKa(a)},a.W=g.Ao(function(){a.X()},100)})},zKa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new T4(b);return(new Promise(function(e){yKa(a,d,function(f){f?(a.Y=!0,n6(a.u,d),q6(a,d),x6(a,c)):g.xo(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):y6(a)})},AKa=function(a,b){var c=a.L.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){jKa(a.u,c,b,d,function(f){f&&f.token&&q6(a,f);e(f)},function(f){r6(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):y6(a)})},yKa=function(a,b,c,d){g.Co(a.I);
a.I=0;lKa(a.u,b,function(e){e||0>d?c(e):a.I=g.Ao(function(){yKa(a,b,c,d-1)},300)})},x6=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
w6(a)&&(g.Co(a.J),a.J=0,0==b?BKa(a):a.J=g.Ao(function(){BKa(a)},b))},BKa=function(a){w6(a)&&a.l.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.ca=c,x6(a,3E4)):(a.Y=!1,a.ca="unknown",oKa(a,b.loungeToken),x6(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.ca="noLoungeTokenResponse";x6(a,3E4)})},CKa=function(a){g.Co(a.I);
a.I=0;g.Co(a.J);a.J=0;a.C();a.C=function(){};
g.Co(a.W)},z6=function(a,b){p6.call(this,a,b,"ManualSession");
this.l=g.Ao((0,g.B)(this.Vo,this,null),150)},A6=function(a,b){g.R.call(this);
this.B=b;this.l=a;this.L=b.appId||"233637DE";this.C=b.theme||"cl";this.W=b.disableCastApi||!1;this.i=null;this.J=!1;this.u=[];this.I=(0,g.B)(this.DO,this)},DKa=function(a,b){return b?g.cb(a.u,function(c){return U4(b,c.label)},a):null},B6=function(a){Z5("Controller",a)},VJa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},C6=function(a){return a.J||!!a.u.length||!!a.i},D6=function(a,b,c){b!=a.i&&(g.Pi(a.i),(a.i=b)?(c?a.V("yt-remote-cast2-receiver-resumed",
b.i):a.V("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.B)(a.QF,a,b)),b.getScreen()?a.V("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.Vo(null)):a.V("yt-remote-cast2-session-change",null))},EKa=function(a){var b=a.l.JB(),c=a.i&&a.i.i;
a=g.Qc(b,function(d){c&&U4(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=DKa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},JKa=function(a,b,c,d){d.disableCastApi?E6("Cannot initialize because disabled by Mdx config."):FKa()?GKa(b,d)&&(F6(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?HKa(a,c):(window.__onGCastApiAvailable=function(e,f){e?HKa(a,c):(G6("Failed to load cast API: "+f),H6(!1),F6(!1),g.Lu("yt-remote-cast-available"),g.Lu("yt-remote-cast-receiver"),
IKa(),c(!1))},d.loadCastApiSetupScript?g.Mo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=f5()&&cJa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?h5():89<=f5()?eJa():(i5(),g5(dJa.map($Ia))))):E6("Cannot initialize because not running Chrome")},IKa=function(){E6("dispose");
var a=I6();a&&a.dispose();g.Da("yt.mdx.remote.cloudview.instance_",null,void 0);KKa(!1);g.Io(J6);J6.length=0},K6=function(){return!!g.Ku("yt-remote-cast-installed")},LKa=function(){var a=g.Ku("yt-remote-cast-receiver");
return a?a.friendlyName:null},MKa=function(){E6("clearCurrentReceiver");
g.Lu("yt-remote-cast-receiver")},NKa=function(){return K6()?I6()?I6().getCastSession():(G6("getCastSelector: Cast is not initialized."),null):(G6("getCastSelector: Cast API is not installed!"),null)},M6=function(){K6()?I6()?L6()?(E6("Requesting cast selector."),I6().requestSession()):(E6("Wait for cast API to be ready to request the session."),J6.push(g.Ho("yt-remote-cast2-api-ready",M6))):G6("requestCastSelector: Cast is not initialized."):G6("requestCastSelector: Cast API is not installed!")},N6=
function(a,b){L6()?I6().setConnectedScreenStatus(a,b):G6("setConnectedScreenStatus called before ready.")},FKa=function(){var a=0<=g.Wc.search(/ (CrMo|Chrome|CriOS)\//);
return g.KA||a},OKa=function(a,b){I6().init(a,b)},GKa=function(a,b){var c=!1;
I6()||(c=new A6(a,b),c.subscribe("yt-remote-cast2-availability-change",function(d){g.Ju("yt-remote-cast-available",d);R4("yt-remote-cast2-availability-change",d)}),c.subscribe("yt-remote-cast2-receiver-selected",function(d){E6("onReceiverSelected: "+d.friendlyName);
g.Ju("yt-remote-cast-receiver",d);R4("yt-remote-cast2-receiver-selected",d)}),c.subscribe("yt-remote-cast2-receiver-resumed",function(d){E6("onReceiverResumed: "+d.friendlyName);
g.Ju("yt-remote-cast-receiver",d);R4("yt-remote-cast2-receiver-resumed",d)}),c.subscribe("yt-remote-cast2-session-change",function(d){E6("onSessionChange: "+V4(d));
d||g.Lu("yt-remote-cast-receiver");R4("yt-remote-cast2-session-change",d)}),g.Da("yt.mdx.remote.cloudview.instance_",c,void 0),c=!0);
E6("cloudview.createSingleton_: "+c);return c},I6=function(){return g.Ha("yt.mdx.remote.cloudview.instance_")},HKa=function(a,b){H6(!0);
F6(!1);OKa(a,function(c){c?(KKa(!0),g.Jo("yt-remote-cast2-api-ready")):(G6("Failed to initialize cast API."),H6(!1),g.Lu("yt-remote-cast-available"),g.Lu("yt-remote-cast-receiver"),IKa());b(c)})},E6=function(a){Z5("cloudview",a)},G6=function(a){Z5("cloudview",a)},H6=function(a){E6("setCastInstalled_ "+a);
g.Ju("yt-remote-cast-installed",a)},L6=function(){return!!g.Ha("yt.mdx.remote.cloudview.apiReady_")},KKa=function(a){E6("setApiReady_ "+a);
g.Da("yt.mdx.remote.cloudview.apiReady_",a,void 0)},F6=function(a){g.Da("yt.mdx.remote.cloudview.initializing_",a,void 0)},O6=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.J=this.L=0;this.i=null;this.hasNext=this.Zi=!1;this.W=this.I=this.l=this.C=0;this.B=NaN;this.u=!1;this.reset(a)},P6=function(a){a.audioTrackId=null;
a.i=null;a.playerState=-1;a.Zi=!1;a.hasNext=!1;a.L=0;a.J=g.Sa();a.C=0;a.l=0;a.I=0;a.W=0;a.B=NaN;a.u=!1},Q6=function(a){return a.Mb()?(g.Sa()-a.J)/1E3:0},R6=function(a,b){a.L=b;
a.J=g.Sa()},S6=function(a){switch(a.playerState){case 1:case 1081:return(g.Sa()-a.J)/1E3+a.L;
case -1E3:return 0}return a.L},T6=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&P6(a)},U6=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Wb(a.i);b.hasPrevious=a.Zi;b.hasNext=a.hasNext;b.playerTime=a.L;b.playerTimeAt=a.J;b.seekableStart=a.C;b.seekableEnd=a.l;b.duration=a.I;b.loadedTime=a.W;b.liveIngestionTime=a.B;return b},W6=function(a,b){g.R.call(this);
this.Ma=0;this.u=a;this.C=[];this.B=new RJa;this.l=this.i=null;this.L=(0,g.B)(this.fN,this);this.I=(0,g.B)(this.Cr,this);this.J=(0,g.B)(this.eN,this);this.W=(0,g.B)(this.mN,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Zz,this),PKa(this))):c=3;0!=c&&(b?this.Zz(c):g.Ao((0,g.B)(function(){this.Zz(c)},this),0));
var d=NKa();d&&V6(this,d);this.subscribe("yt-remote-cast2-session-change",this.W)},X6=function(a){return new O6(a.u.getPlayerContextData())},PKa=function(a){g.Ab("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.u.subscribe(b,g.Qa(this.AO,b),this))},a)},QKa=function(a){g.Ab(a.C,function(b){this.u.unsubscribeByKey(b)},a);
a.C.length=0},Y6=function(a){return 1==a.getState()},Z6=function(a,b){var c=a.B;
50>c.i.length+c.l.length&&a.B.l.push(b)},a7=function(a,b,c){var d=X6(a);
R6(d,c);-1E3!=d.playerState&&(d.playerState=b);$6(a,d)},b7=function(a,b,c){a.u.sendMessage(b,c)},$6=function(a,b){QKa(a);
a.u.setPlayerContextData(U6(b));PKa(a)},V6=function(a,b){a.l&&(a.l.removeUpdateListener(a.L),a.l.removeMediaListener(a.I),a.Cr(null));
a.l=b;a.l&&(Z5("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.L),a.l.addMediaListener(a.I),a.l.media.length&&a.Cr(a.l.media[0]))},RKa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=X6(a);b.contentId!=d.videoId&&Z5("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;R6(d,a.i.getEstimatedTime());$6(a,d)}else Z5("CP","No cast media video. Ignoring state update.")},c7=function(a,b,c){return(0,g.B)(function(d){this.Id("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Id("Retrying "+b+" using MDx browser channel."),b7(this,b,c))},a)},d7=function(a,b,c){g.R.call(this);
this.C=NaN;this.ca=!1;this.L=this.J=this.X=this.Y=NaN;this.W=[];this.B=this.I=this.u=this.Hb=this.i=null;this.ia=a;this.W.push(g.bp(window,"beforeunload",(0,g.B)(this.rL,this)));this.l=[];this.Hb=new O6;this.ga=b.id;this.ea=b.idType;this.i=SKa(this,c);this.i.subscribe("handlerOpened",this.jN,this);this.i.subscribe("handlerClosed",this.gN,this);this.i.subscribe("handlerError",this.hN,this);this.i.subscribe("handlerMessage",this.iN,this);this.i.cv(b.token);this.subscribe("remoteQueueChange",function(){var d=
this.Hb.videoId;g.Mu()&&g.Ju("yt-remote-session-video-id",d)},this)},e7=function(a){Z5("conn",a)},SKa=function(a,b){return new S5(W5(a.ia,"/bc"),b,!1,function(){return a.OB()},"shortLived"==a.ea)},f7=function(a,b){a.V("proxyStateChange",b)},TKa=function(a){a.C=g.Ao((0,g.B)(function(){e7("Connecting timeout");
this.xo(1)},a),2E4)},g7=function(a){g.Co(a.C);
a.C=NaN},h7=function(a){g.Co(a.Y);
a.Y=NaN},UKa=function(a){i7(a);
a.X=g.Ao((0,g.B)(function(){j7(this,"getNowPlaying")},a),2E4)},i7=function(a){g.Co(a.X);
a.X=NaN},WKa=function(a,b){b&&(g7(a),h7(a));
var c=U5(a.i)&&isNaN(a.C);b==c?b&&(f7(a,1),j7(a,"getSubtitlesTrack")):b?(a.JD()&&a.Hb.reset(),f7(a,1),j7(a,"getNowPlaying"),VKa(a)):a.xo(1)},XKa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Hb.videoId&&(g.Pb(b.params)?a.Hb.i=null:a.Hb.i=b.params,a.V("remotePlayerChange"))},YKa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Hb.listId=b.params.listId||a.Hb.listId;T6(a.Hb,c,d);a.V("remoteQueueChange")},$Ka=function(a,b){b.params=b.params||{};
YKa(a,b);ZKa(a,b);a.V("autoplayDismissed")},ZKa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
R6(a.Hb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Hb.playerState&&(c=-1E3);a.Hb.playerState=c;c=Number(b.params.loadedTime);a.Hb.W=isNaN(c)?0:c;c=Number(b.params.duration);a.Hb.I=isNaN(c)?0:c;c=a.Hb;var d=Number(b.params.liveIngestionTime);c.B=d;c.u=isNaN(d)?!1:!0;c=a.Hb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.l=isNaN(e)?0:e;1==a.Hb.playerState?UKa(a):i7(a);a.V("remotePlayerChange")},aLa=function(a,b){if(-1E3!=
a.Hb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Hb.playerState=c;c=parseInt(b.params.currentTime,10);R6(a.Hb,isNaN(c)?0:c);a.V("remotePlayerChange")}},bLa=function(a,b){var c="true"==b.params.muted;
a.Hb.volume=parseInt(b.params.volume,10);a.Hb.muted=c;a.V("remotePlayerChange")},cLa=function(a,b){a.I=b.params.videoId;
a.V("nowAutoplaying",parseInt(b.params.timeout,10))},dLa=function(a,b){var c="true"==b.params.hasNext;
a.Hb.Zi="true"==b.params.hasPrevious;a.Hb.hasNext=c;a.V("previousNextChange")},VKa=function(a){g.Co(a.L);
a.L=g.Ao((0,g.B)(a.xo,a,1),864E5)},j7=function(a,b,c){c?e7("Sending: action="+b+", params="+g.Qj(c)):e7("Sending: action="+b);
a.i.sendMessage(b,c)},k7=function(a){c6.call(this,"ScreenServiceProxy");
this.Jf=a;this.i=[];this.i.push(this.Jf.$_s("screenChange",(0,g.B)(this.VJ,this)));this.i.push(this.Jf.$_s("onlineScreenChange",(0,g.B)(this.hO,this)))},hLa=function(a,b){VIa();
if(!e5||!e5.get("yt-remote-disable-remote-module-for-dev")){b=g.P("MDX_CONFIG")||b;NIa();c5();l7||(l7=new V5(b?b.loungeApiHost:void 0),WIa()&&(l7.i="/api/loungedev"));m7||(m7=g.Ha("yt.mdx.remote.deferredProxies_")||[],g.Da("yt.mdx.remote.deferredProxies_",m7,void 0));eLa();var c=n7();if(!c){var d=new m6(l7);g.Da("yt.mdx.remote.screenService_",d,void 0);c=n7();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,disableCastApi:b.disableCastApi,
enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken});JKa(a,d,function(h){h?o7()&&N6(o7(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){R4("yt-remote-receiver-availability-change")})},e)}if(b&&!g.Ha("yt.mdx.remote.initialized_")){g.Da("yt.mdx.remote.initialized_",!0,void 0);
p7("Initializing: "+g.Qj(b));q7.push(g.Ho("yt-remote-cast2-availability-change",function(){R4("yt-remote-receiver-availability-change")}));
q7.push(g.Ho("yt-remote-cast2-receiver-selected",function(){r7(null);R4("yt-remote-auto-connect","cast-selector-receiver")}));
q7.push(g.Ho("yt-remote-cast2-receiver-resumed",function(){R4("yt-remote-receiver-resumed","cast-selector-receiver")}));
q7.push(g.Ho("yt-remote-cast2-session-change",fLa));q7.push(g.Ho("yt-remote-connection-change",function(h){h?N6(o7(),"YouTube TV"):s7()||(N6(null,null),MKa())}));
e=t7();b.isAuto&&(e.id+="#dial");g.Qo("desktop_enable_autoplay")&&(e.capabilities=["atp"]);e.name=b.device;e.app=b.app;var f=b.theme;f&&(e.theme=f);p7(" -- with channel params: "+g.Qj(e));e?(g.Ju("yt-remote-session-app",e.app),g.Ju("yt-remote-session-name",e.name)):(g.Lu("yt-remote-session-app"),g.Lu("yt-remote-session-name"));g.Da("yt.mdx.remote.channelParams_",e,void 0);c.start();o7()||gLa()}}},iLa=function(){var a=n7().Jf.$_gos();
var b=u7();b&&v7()&&(Y4(a,b)||a.push(b));return MIa(a)},w7=function(){var a=jLa();
!a&&K6()&&LKa()&&(a={key:"cast-selector-receiver",name:LKa()});return a},jLa=function(){var a=iLa(),b=u7();
b||(b=s7());return g.cb(a,function(c){return b&&U4(b,c.key)?!0:!1})},u7=function(){var a=o7();
if(!a)return null;var b=n7().Ng();return Z4(b,a)},fLa=function(a){p7("remote.onCastSessionChange_: "+V4(a));
if(a){var b=u7();if(b&&b.id==a.id){if(N6(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))x7&&(x7.token=a),(b=v7())&&b.cv(a)}else b&&y7(),z7(a,1)}else v7()&&y7()},y7=function(){L6()?I6().stopSession():G6("stopSession called before API ready.");
var a=v7();a&&(a.disconnect(1),A7(null))},B7=function(){var a=v7();
return!!a&&3!=a.getProxyState()},p7=function(a){Z5("remote",a)},n7=function(){if(!C7){var a=g.Ha("yt.mdx.remote.screenService_");
C7=a?new k7(a):null}return C7},o7=function(){return g.Ha("yt.mdx.remote.currentScreenId_")},kLa=function(a){g.Da("yt.mdx.remote.currentScreenId_",a,void 0)},lLa=function(){return g.Ha("yt.mdx.remote.connectData_")},r7=function(a){g.Da("yt.mdx.remote.connectData_",a,void 0)},v7=function(){return g.Ha("yt.mdx.remote.connection_")},A7=function(a){var b=v7();
r7(null);a||kLa("");g.Da("yt.mdx.remote.connection_",a,void 0);m7&&(g.Ab(m7,function(c){c(a)}),m7.length=0);
b&&!a?R4("yt-remote-connection-change",!1):!b&&a&&R4("yt-remote-connection-change",!0)},s7=function(){var a=g.Mu();
if(!a)return null;var b=n7();if(!b)return null;b=b.Ng();return Z4(b,a)},z7=function(a,b){o7();
u7()&&u7();if(D7)x7=a;else{kLa(a.id);var c=new d7(l7,a,t7());c.connect(b,lLa());c.subscribe("beforeDisconnect",function(d){R4("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){v7()&&(v7(),A7(null))});
c.subscribe("browserChannelAuthError",function(){var d=u7();d&&"shortLived"==d.idType&&(L6()?I6().handleBrowserChannelAuthError():G6("refreshLoungeToken called before API ready."))});
A7(c)}},gLa=function(){var a=s7();
a?(p7("Resume connection to: "+V4(a)),z7(a,0)):(d5(),MKa(),p7("Skipping connecting because no session screen found."))},eLa=function(){var a=t7();
if(g.Pb(a)){a=b5();var b=g.Ku("yt-remote-session-name")||"",c=g.Ku("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Da("yt.mdx.remote.channelParams_",a,void 0)}},t7=function(){return g.Ha("yt.mdx.remote.channelParams_")||{}},E7=function(a,b,c){g.E.call(this);
var d=this;this.l=a;this.G=b;this.xb=c;this.events=new g.yN(this);this.X=this.events.N(this.G,"onVolumeChange",function(e){mLa(d,e)});
this.C=!1;this.suggestion=null;this.I=new g.DK(64);this.i=new g.M(this.UG,500,this);this.u=new g.M(this.VG,1E3,this);this.L=new j5(this.YQ,0,this);this.B={};this.W=new g.M(this.xH,1E3,this);this.J=new k5(this.seekTo,1E3,this);this.Y=g.Ia;g.I(this,this.events);this.events.N(b,"onCaptionsTrackListChanged",this.QN);this.events.N(b,"captionschanged",this.cN);this.events.N(b,"captionssettingschanged",this.aH);this.events.N(b,"videoplayerreset",this.Mu);this.events.N(b,"mdxautoplaycancel",function(){d.xb.dD()});
a=this.xb;a.na();a.subscribe("proxyStateChange",this.LF,this);a.subscribe("remotePlayerChange",this.Ir,this);a.subscribe("remoteQueueChange",this.Mu,this);a.subscribe("previousNextChange",this.IF,this);a.subscribe("nowAutoplaying",this.DF,this);a.subscribe("autoplayDismissed",this.dF,this);g.I(this,this.i);g.I(this,this.u);g.I(this,this.L);g.I(this,this.W);g.I(this,this.J);this.aH();this.Mu();this.Ir()},mLa=function(a,b){if(F7(a)){a.xb.unsubscribe("remotePlayerChange",a.Ir,a);
var c=Math.round(b.volume),d=!!b.muted,e=X6(a.xb);if(c!==e.volume||d!==e.muted)a.xb.setVolume(c,d),a.W.start();a.xb.subscribe("remotePlayerChange",a.Ir,a)}},nLa=function(a){a.Cb(0);
a.i.stop();a.ub(new g.DK(64))},G7=function(a,b){if(F7(a)&&!a.C){var c=null;
b&&(c={style:a.G.getSubtitlesUserSettings()},g.Yb(c,b));a.xb.NB(a.G.getVideoData(1).videoId,c);a.B=X6(a.xb).i}},H7=function(a,b){var c=a.G.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.G.getVideoData(1);a.xb.playVideo(c.videoId,b,d,e,c.playerParams,c.ia,zIa(c));a.ub(new g.DK(1))},oLa=function(a,b){if(b){var c=a.G.getOption("captions","tracklist",{cE:1});
c&&c.length?(a.G.setOption("captions","track",b),a.C=!1):(a.G.loadModule("captions"),a.C=!0)}else a.G.setOption("captions","track",{})},F7=function(a){return X6(a.xb).videoId===a.G.getVideoData(1).videoId},I7=function(){g.X.call(this,{D:"div",
K:"ytp-mdx-manual-pairing-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-title",ba:"\u6211\u5011\u5373\u5c07\u6dd8\u6c70\u5728\u7db2\u9801\u4e0a\u900f\u904e\u4ee3\u78bc\u9023\u7d50\u96fb\u8996\u7684\u529f\u80fd"},{D:"div",K:"ytp-mdx-manual-pairing-popup-buttons",S:[{D:"button",ka:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],ba:"\u77ad\u89e3\u8a73\u60c5"},{D:"button",ka:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],
ba:"\u78ba\u5b9a"}]}]}]});this.i=new g.mM(this,250);this.learnMoreButton=this.ha("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ha("ytp-mdx-manual-pairing-popup-ok");g.I(this,this.i);this.N(this.learnMoreButton,"click",this.l);this.N(this.okButton,"click",this.u)},J7=function(){g.X.call(this,{D:"div",
K:"ytp-mdx-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-popup-title",ba:"\u4f60\u5df2\u767b\u51fa\u5e33\u6236"},{D:"div",K:"ytp-mdx-popup-description",ba:"\u4f60\u89c0\u770b\u7684\u5f71\u7247\u53ef\u80fd\u6703\u65b0\u589e\u81f3\u96fb\u8996\u7684\u89c0\u770b\u8a18\u9304\uff0c\u4e26\u5f71\u97ff\u7cfb\u7d71\u5728\u96fb\u8996\u4e0a\u63a8\u85a6\u7684\u5167\u5bb9\u3002\u5982\u8981\u907f\u514d\u9019\u7a2e\u60c5\u6cc1\uff0c\u8acb\u6309\u4e00\u4e0b [\u53d6\u6d88] \u4e26\u5728\u96fb\u8166\u4e0a\u767b\u5165 YouTube\u3002"},
{D:"div",K:"ytp-mdx-privacy-popup-buttons",S:[{D:"button",ka:["ytp-button","ytp-mdx-privacy-popup-cancel"],ba:"\u53d6\u6d88"},{D:"button",ka:["ytp-button","ytp-mdx-privacy-popup-confirm"],ba:"\u78ba\u8a8d"}]}]}]});this.i=new g.mM(this,250);this.cancelButton=this.ha("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ha("ytp-mdx-privacy-popup-confirm");g.I(this,this.i);this.N(this.cancelButton,"click",this.l);this.N(this.confirmButton,"click",this.u)},K7=function(a){g.X.call(this,{D:"div",
K:"ytp-remote",S:[{D:"div",K:"ytp-remote-display-status",S:[{D:"div",K:"ytp-remote-display-status-icon",S:[g.dna()]},{D:"div",K:"ytp-remote-display-status-text",ba:"{{statustext}}"}]}]});this.api=a;this.i=new g.mM(this,250);g.I(this,this.i);this.N(a,"presentingplayerstatechange",this.l);pLa(this,a.Ya())},pLa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.W(b,128)?g.bK("\u300c$RECEIVER_NAME\u300d\u767c\u751f\u932f\u8aa4",c):b.Mb()||g.W(b,4)?g.bK("\u6b63\u5728\u300c$RECEIVER_NAME\u300d\u4e0a\u64ad\u653e",c):g.bK("\u5df2\u9023\u7dda\u81f3\u300c$RECEIVER_NAME\u300d",c);a.Ba("statustext",c);a.i.show()}else a.i.hide()},L7=function(a,b){g.qQ.call(this,"\u64ad\u653e\u87a2\u5e55\uff1a",0,a,b);
this.G=a;this.Pl={};this.N(a,"onMdxReceiversChange",this.C);this.N(a,"presentingplayerstatechange",this.C);this.C()},M7=function(a){g.GN.call(this,a);
this.fi={key:X4(),name:"\u9019\u53f0\u96fb\u8166"};this.kh=null;this.subscriptions=[];this.Az=this.xb=null;this.Pl=[this.fi];this.Zk=this.fi;this.Pc=new g.DK(64);this.yE=0;this.Pe=-1;this.Zo=null;this.Lr=this.qu=!1;this.En=this.qp=null;if(!g.$C(this.player.T())){a=this.player;var b=g.mN(a);b&&(b=b.gn())&&(b=new L7(a,b),g.I(this,b));b=new K7(a);g.I(this,b);g.wN(a,b.element,4);this.qp=new J7;g.I(this,this.qp);g.wN(a,this.qp.element,4);g.T(this.player.T().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.T(this.player.T().experiments,"deprecate_pair_servlet_enabled")&&(this.Zo=new I7,g.I(this,this.Zo),g.wN(a,this.Zo.element,4));this.Lr=!!s7();this.qu=!!g.Ku("yt-remote-manual-pairing-warning-shown")}},N7=function(a){a.En&&(a.player.removeEventListener("presentingplayerstatechange",a.En),a.En=null)},qLa=function(a,b,c){a.Pc=c;
a.player.V("presentingplayerstatechange",new g.IJ(c,b))},rLa=function(a,b,c){var d=!1;
1===b?d=!a.Lr:2===b&&(d=!a.qu);d&&g.KJ(c,8)&&(a.player.pauseVideo(),N7(a))},O7=function(a,b){if(b.key!==a.Zk.key)if(b.key===a.fi.key)y7();
else{if(a.Zo&&!a.qu&&b!==a.fi&&"cast-selector-receiver"!==b.key&&g.tD(a.player.T()))sLa(a);else{var c;(c=!g.T(a.player.T().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.P("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.P("SESSION_INDEX")&&!g.P("LOGGED_IN")))||a.Lr||!a.qp);(c?0:g.tD(a.player.T())||g.xD(a.player.T()))&&tLa(a)}a.Zk=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.T(a.player.T().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=f.Na(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.ia,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=zIa(c))&&(d.locationInfo=c);c=d}p7("Connecting to: "+g.Qj(b));"cast-selector-receiver"==b.key?(r7(c||null),c=c||null,
L6()?I6().setLaunchParams(c):G6("setLaunchParams called before ready.")):!c&&B7()&&o7()==b.key?R4("yt-remote-connection-change",!0):(y7(),r7(c||null),c=n7().Ng(),(c=Z4(c,b.key))&&z7(c,1))}},tLa=function(a){a.player.Ya().Mb()?a.player.pauseVideo():(a.En=function(b){rLa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.En));
a.qp&&a.qp.Gc();v7()||(D7=!0)},sLa=function(a){a.player.Ya().Mb()?a.player.pauseVideo():(a.En=function(b){rLa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.En));
a.Zo&&a.Zo.Gc();v7()||(D7=!0)},oJa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},z5={"'":"\\'"},uLa={},IIa={XR:"atp",m1:"ska",h0:"que",yZ:"mus",l1:"sus",PV:"dsp",A0:"seq",cZ:"mic",PU:"dpa"},e5,a5="",bJa=XIa("loadCastFramework")||XIa("loadCastApplicationFramework"),dJa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ta(j5,g.E);g.k=j5.prototype;g.k.pg=function(a){this.B=arguments;this.i=!1;this.ib?this.u=g.Sa()+this.Kf:this.ib=g.Mm(this.C,this.Kf)};
g.k.stop=function(){this.ib&&(g.A.clearTimeout(this.ib),this.ib=null);this.u=null;this.i=!1;this.B=[]};
g.k.pause=function(){++this.l};
g.k.resume=function(){this.l&&(--this.l,!this.l&&this.i&&(this.i=!1,this.I.apply(null,this.B)))};
g.k.da=function(){this.stop();j5.Gd.da.call(this)};
g.k.LJ=function(){this.u?(this.ib=g.Mm(this.C,this.u-g.Sa()),this.u=null):(this.ib=null,this.l?this.i=!0:(this.i=!1,this.I.apply(null,this.B)))};g.u(k5,g.E);g.k=k5.prototype;g.k.pg=function(a){this.u=arguments;this.ib||this.l?this.i=!0:l5(this)};
g.k.stop=function(){this.ib&&(g.A.clearTimeout(this.ib),this.ib=null,this.i=!1,this.u=null)};
g.k.pause=function(){this.l++};
g.k.resume=function(){this.l--;this.l||!this.i||this.ib||(this.i=!1,l5(this))};
g.k.da=function(){g.E.prototype.da.call(this);this.stop()};n5.prototype.stringify=function(a){return g.A.JSON.stringify(a,void 0)};
n5.prototype.parse=function(a){return g.A.JSON.parse(a,void 0)};var p5=new g.bm;g.u(fJa,g.Il);r5.prototype.i=null;r5.prototype.getOptions=function(){var a;(a=this.i)||(a={},hJa(this)&&(a[0]=!0,a[1]=!0),a=this.i=a);return a};var P7;g.Ta(gJa,r5);P7=new gJa;g.k=s5.prototype;g.k.km=null;g.k.yi=!1;g.k.Kp=null;g.k.KA=null;g.k.tp=null;g.k.Ep=null;g.k.Tk=null;g.k.Sl=null;g.k.Fn=null;g.k.Ee=null;g.k.Es=0;g.k.Ci=null;g.k.Fv=null;g.k.Nk=null;g.k.bq=-1;g.k.KG=!0;g.k.Nm=!1;g.k.xw=0;g.k.Su=null;var mJa={},v5={};g.k=s5.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.ZP=function(a){a=a.target;var b=this.Su;b&&3==E5(a)?b.pg():this.HH(a)};
g.k.HH=function(a){try{if(a==this.Ee)a:{var b=E5(this.Ee),c=this.Ee.I,d=this.Ee.getStatus();if(g.Be&&!g.de(10)||g.De&&!g.ce("420+")){if(4>b)break a}else if(3>b||3==b&&!g.vg&&!G5(this.Ee))break a;this.Nm||4!=b||7==c||(8==c||0>=d?this.i.ii(3):this.i.ii(2));A5(this);var e=this.Ee.getStatus();this.bq=e;var f=G5(this.Ee);(this.yi=200==e)?(4==b&&x5(this),this.I?(nJa(this,b,f),g.vg&&this.yi&&3==b&&(this.B.za(this.u,"tick",this.SP),this.u.start())):w5(this,f),this.yi&&!this.Nm&&(4==b?this.i.Vs(this):(this.yi=
!1,u5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Nk=3,q5(13)):(this.Nk=0,q5(14)),x5(this),y5(this))}}catch(h){this.Ee&&G5(this.Ee)}finally{}};
g.k.SP=function(){var a=E5(this.Ee),b=G5(this.Ee);this.Es<b.length&&(A5(this),nJa(this,a,b),this.yi&&4!=a&&u5(this))};
g.k.vP=function(a){o5((0,g.B)(this.uP,this,a),0)};
g.k.uP=function(a){this.Nm||(A5(this),w5(this,a),u5(this))};
g.k.VF=function(a){o5((0,g.B)(this.tP,this,a),0)};
g.k.tP=function(a){this.Nm||(x5(this),this.yi=a,this.i.Vs(this),this.i.ii(4))};
g.k.cancel=function(){this.Nm=!0;x5(this)};
g.k.DP=function(){this.Kp=null;var a=g.Sa();0<=a-this.KA?(2!=this.Ep&&this.i.ii(3),x5(this),this.Nk=2,q5(18),y5(this)):qJa(this,this.KA-a)};
g.k.getLastError=function(){return this.Nk};g.Ta(C5,g.bm);var xJa=/^https?$/i,vLa=["POST","PUT"];g.k=C5.prototype;
g.k.send=function(a,b,c,d){if(this.i)throw Error("[goog.net.XhrIo] Object is active with another request="+this.W+"; newUri="+a);b=b?b.toUpperCase():"GET";this.W=a;this.u="";this.I=0;this.Aa=b;this.ga=!1;this.B=!0;this.i=this.ea?iJa(this.ea):iJa(P7);this.ca=this.ea?this.ea.getOptions():P7.getOptions();this.i.onreadystatechange=(0,g.B)(this.JF,this);try{Q4(F5(this,"Opening Xhr")),this.la=!0,this.i.open(b,String(a),!0),this.la=!1}catch(f){Q4(F5(this,"Error opening Xhr: "+f.message));wJa(this,f);return}a=
c||"";var e=this.headers.clone();d&&EIa(d,function(f,h){e.set(h,f)});
d=g.cb(e.qh(),uJa);c=g.A.FormData&&a instanceof g.A.FormData;!g.fb(vLa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.i.setRequestHeader(h,f)},this);
this.Ca&&(this.i.responseType=this.Ca);"withCredentials"in this.i&&this.i.withCredentials!==this.ia&&(this.i.withCredentials=this.ia);try{zJa(this),0<this.J&&(this.Y=tJa(this.i),Q4(F5(this,"Will abort after "+this.J+"ms if incomplete, xhr2 "+this.Y)),this.Y?(this.i.timeout=this.J,this.i.ontimeout=(0,g.B)(this.HB,this)):this.X=g.Mm(this.HB,this.J,this)),Q4(F5(this,"Sending request")),this.L=!0,this.i.send(a),this.L=!1}catch(f){Q4(F5(this,"Send error: "+f.message)),wJa(this,f)}};
g.k.HB=function(){"undefined"!=typeof g.P_&&this.i&&(this.u="Timed out after "+this.J+"ms, aborting",this.I=8,F5(this,this.u),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.i&&this.B&&(F5(this,"Aborting"),this.B=!1,this.C=!0,this.i.abort(),this.C=!1,this.I=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),D5(this))};
g.k.da=function(){this.i&&(this.B&&(this.B=!1,this.C=!0,this.i.abort(),this.C=!1),D5(this,!0));C5.Gd.da.call(this)};
g.k.JF=function(){this.na()||(this.la||this.L||this.C?yJa(this):this.CO())};
g.k.CO=function(){yJa(this)};
g.k.isActive=function(){return!!this.i};
g.k.isComplete=function(){return 4==E5(this)};
g.k.getStatus=function(){try{return 2<E5(this)?this.i.status:-1}catch(a){return-1}};
g.k.getResponseHeader=function(a){if(this.i&&this.isComplete())return a=this.i.getResponseHeader(a),null===a?void 0:a};
g.k.getLastError=function(){return"string"===typeof this.u?this.u:String(this.u)};g.k=AJa.prototype;g.k.yw=null;g.k.Cg=null;g.k.Tu=!1;g.k.WG=null;g.k.At=null;g.k.Py=null;g.k.zw=null;g.k.Ma=null;g.k.Pj=-1;g.k.cq=null;g.k.mq=null;g.k.connect=function(a){this.zw=a;a=H5(this.i,null,this.zw);q5(3);this.WG=g.Sa();var b=this.i.J;null!=b?(this.cq=b[0],(this.mq=b[1])?(this.Ma=1,BJa(this)):(this.Ma=2,J5(this))):(O4(a,"MODE","init"),this.Cg=new s5(this,void 0,void 0,void 0),this.Cg.km=this.yw,t5(this.Cg,a,!1,null,!0),this.Ma=0)};
g.k.CK=function(a){if(a)this.Ma=2,J5(this);else{q5(4);var b=this.i;b.Ji=b.Xk.Pj;Q5(b,9)}a&&this.ii(2)};
g.k.Ax=function(a){return this.i.Ax(a)};
g.k.abort=function(){this.Cg&&(this.Cg.cancel(),this.Cg=null);this.Pj=-1};
g.k.IB=function(){return!1};
g.k.MF=function(a,b){this.Pj=a.bq;if(0==this.Ma)if(b){try{var c=this.l.parse(b)}catch(d){c=this.i;c.Ji=this.Pj;Q5(c,2);return}this.cq=c[0];this.mq=c[1]}else c=this.i,c.Ji=this.Pj,Q5(c,2);else if(2==this.Ma)if(this.Tu)q5(7),this.Py=g.Sa();else if("11111"==b){if(q5(6),this.Tu=!0,this.At=g.Sa(),c=this.At-this.WG,!g.Be||g.de(10)||500>c)this.Pj=200,this.Cg.cancel(),q5(12),I5(this.i,this,!0)}else q5(8),this.At=this.Py=g.Sa(),this.Tu=!1};
g.k.Vs=function(){this.Pj=this.Cg.bq;if(this.Cg.yi)0==this.Ma?this.mq?(this.Ma=1,BJa(this)):(this.Ma=2,J5(this)):2==this.Ma&&((!g.Be||g.de(10)?!this.Tu:200>this.Py-this.At)?(q5(11),I5(this.i,this,!1)):(q5(12),I5(this.i,this,!0)));else{0==this.Ma?q5(9):2==this.Ma&&q5(10);var a=this.i;this.Cg.getLastError();a.Ji=this.Pj;Q5(a,2)}};
g.k.ds=function(){return this.i.ds()};
g.k.isActive=function(){return this.i.isActive()};
g.k.ii=function(a){this.i.ii(a)};g.k=K5.prototype;g.k.Ii=null;g.k.Gq=null;g.k.qg=null;g.k.Zd=null;g.k.Aw=null;g.k.Bt=null;g.k.wC=null;g.k.Ws=null;g.k.Ar=0;g.k.uM=0;g.k.Cf=null;g.k.kl=null;g.k.Sj=null;g.k.Wm=null;g.k.Xk=null;g.k.Dv=null;g.k.Uo=-1;g.k.xE=-1;g.k.Ji=-1;g.k.Bo=0;g.k.lo=0;g.k.Om=8;g.Ta(DJa,g.Il);g.Ta(EJa,g.Il);g.k=K5.prototype;g.k.connect=function(a,b,c,d,e){q5(0);this.Aw=b;this.Gq=c||{};d&&void 0!==e&&(this.Gq.OSID=d,this.Gq.OAID=e);this.C?(o5((0,g.B)(this.PC,this,a),100),IJa(this)):this.PC(a)};
g.k.PC=function(a){this.Xk=new AJa(this);this.Xk.yw=this.Ii;this.Xk.l=this.B;this.Xk.connect(a)};
g.k.IB=function(){return 0==this.Ma};
g.k.getState=function(){return this.Ma};
g.k.TF=function(a){this.kl=null;MJa(this,a)};
g.k.SF=function(){this.Sj=null;this.Zd=new s5(this,this.l,"rpc",this.I);this.Zd.km=this.Ii;this.Zd.xw=0;var a=this.wC.clone();M4(a,"RID","rpc");M4(a,"SID",this.l);M4(a,"CI",this.Dv?"0":"1");M4(a,"AID",this.Uo);L5(this,a);if(!g.Be||g.de(10))M4(a,"TYPE","xmlhttp"),t5(this.Zd,a,!0,this.Ws,!1);else{M4(a,"TYPE","html");var b=this.Zd,c=!!this.Ws;b.Ep=3;b.Tk=N4(a.clone());pJa(b,c)}};
g.k.MF=function(a,b){if(0!=this.Ma&&(this.Zd==a||this.qg==a))if(this.Ji=a.bq,this.qg==a&&3==this.Ma)if(7<this.Om){try{var c=this.B.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Sj){if(this.Zd)if(this.Zd.tp+3E3<this.qg.tp)N5(this),this.Zd.cancel(),this.Zd=null;else break a;P5(this);q5(19)}}else this.xE=c[1],0<this.xE-this.Uo&&37500>c[2]&&this.Dv&&0==this.lo&&!this.Wm&&(this.Wm=o5((0,g.B)(this.YM,this),6E3));else Q5(this,11)}else b!=uLa.DU.i&&Q5(this,11);else if(this.Zd==
a&&N5(this),!g.rc(b)){c=this.B.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.Uo=e[0];e=e[1];2==this.Ma?"c"==e[0]?(this.l=e[1],this.Ws=e[2],e=e[3],null!=e?this.Om=e:this.Om=6,this.Ma=3,this.Cf&&this.Cf.LC(),this.wC=H5(this,this.ds()?this.Ws:null,this.Aw),NJa(this)):"stop"==e[0]&&Q5(this,7):3==this.Ma&&("stop"==e[0]?Q5(this,7):"noop"!=e[0]&&this.Cf&&this.Cf.KC(e),this.lo=0)}}};
g.k.YM=function(){null!=this.Wm&&(this.Wm=null,this.Zd.cancel(),this.Zd=null,P5(this),q5(20))};
g.k.Vs=function(a){if(this.Zd==a){N5(this);this.Zd=null;var b=2}else if(this.qg==a)this.qg=null,b=1;else return;this.Ji=a.bq;if(0!=this.Ma)if(a.yi)1==b?(b=p5,b.dispatchEvent(new DJa(b,a.Fn?a.Fn.length:0,g.Sa()-a.tp,this.Bo)),M5(this),this.u.length=0):NJa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ji)){if(d=1==b)this.qg||this.kl||1==this.Ma||2<=this.Bo?d=!1:(this.kl=o5((0,g.B)(this.TF,this,a),OJa(this,this.Bo)),this.Bo++,d=!0);d=!(d||2==b&&P5(this))}if(d)switch(c){case 1:Q5(this,
5);break;case 4:Q5(this,10);break;case 3:Q5(this,6);break;case 7:Q5(this,12);break;default:Q5(this,2)}}};
g.k.WK=function(a){if(!g.fb(arguments,this.Ma))throw Error("Unexpected channel state: "+this.Ma);};
g.k.HQ=function(a){a?q5(2):(q5(1),PJa(this,8))};
g.k.Ax=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new C5;a.ia=!1;return a};
g.k.isActive=function(){return!!this.Cf&&this.Cf.isActive(this)};
g.k.ii=function(a){var b=p5;b.dispatchEvent(new EJa(b,a))};
g.k.ds=function(){return!(!g.Be||g.de(10))};
g.k=QJa.prototype;g.k.LC=function(){};
g.k.KC=function(){};
g.k.JC=function(){};
g.k.jx=function(){};
g.k.tD=function(){return{}};
g.k.isActive=function(){return!0};g.k=RJa.prototype;g.k.isEmpty=function(){return g.gb(this.i)&&g.gb(this.l)};
g.k.clear=function(){this.i=[];this.l=[]};
g.k.contains=function(a){return g.fb(this.i,a)||g.fb(this.l,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.WCa)(b,a);0<=c?(g.jb(b,c),b=!0):b=!1;return b||g.kb(this.l,a)};
g.k.tg=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};g.Ta(R5,g.E);g.k=R5.prototype;g.k.nP=function(){this.Kf=Math.min(3E5,2*this.Kf);this.u();this.l&&this.start()};
g.k.start=function(){var a=this.Kf+15E3*Math.random();g.ln(this.i,a);this.l=g.Sa()+a};
g.k.stop=function(){this.i.stop();this.l=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Kf=5E3};g.Ta(S5,QJa);g.k=S5.prototype;g.k.subscribe=function(a,b,c){return this.u.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.u.unsubscribe(a,b,c)};
g.k.Pf=function(a){return this.u.Pf(a)};
g.k.V=function(a,b){return this.u.V.apply(this.u,arguments)};
g.k.dispose=function(){this.X||(this.X=!0,g.Pi(this.u),UJa(this),g.Pi(this.l),this.l=null,this.Y=function(){return""})};
g.k.na=function(){return this.X};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.W="";this.l.stop();this.C=a||null;this.B=b||0;a=this.ca+"/test";b=this.ca+"/bind";var d=new K5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.ea),e=this.i;e&&(e.Cf=null);d.Cf=this;this.i=d;T5(this);if(this.i){d=g.P("ID_TOKEN");var f=this.i.Ii||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.Ii=f}e?(3!=e.getState()&&0==KJa(e)||e.getState(),this.i.connect(a,b,this.I,e.l,e.Uo)):c?this.i.connect(a,
b,this.I,c.sessionId,c.arrayId):this.i.connect(a,b,this.I)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Yb(c,b);this.l.isActive()||2==(this.i?this.i.getState():0)?this.J.push(c):U5(this)&&(T5(this),JJa(this.i,c))};
g.k.LC=function(){this.l.reset();this.C=null;this.B=0;if(this.J.length){var a=this.J;this.J=[];for(var b=0,c=a.length;b<c;++b)JJa(this.i,a[b])}this.V("handlerOpened")};
g.k.JC=function(a){var b=2==a&&401==this.i.Ji;4==a||b||this.l.start();this.V("handlerError",a,b)};
g.k.jx=function(a){if(!this.l.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.J.push(d)}};
g.k.tD=function(){var a={v:2};this.W&&(a.gsessionid=this.W);0!=this.B&&(a.ui=""+this.B);0!=this.L&&(a.ui=""+this.L);this.C&&g.Yb(a,this.C);return a};
g.k.KC=function(a){"S"==a[0]?this.W=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),HJa(this.i)):this.V("handlerMessage",new SJa(a[0],a[1]))};
g.k.cv=function(a){(this.I.loungeIdToken=a)||this.l.stop();if(this.ia&&this.i){var b=this.i.Ii||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.Ii=b}};
g.k.jQ=function(){this.l.isActive();0==KJa(this.i)&&this.connect(this.C,this.B)};V5.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
V5.prototype.u=function(a,b){a(Error("Request error: "+b.status))};
V5.prototype.C=function(a){a(Error("request timed out"))};var aKa=g.Sa(),Y5=null,a6=Array(50),$5=-1,b6=!1;g.Ta(c6,g.R);c6.prototype.Ng=function(){return this.screens};
c6.prototype.contains=function(a){return!!Y4(this.screens,a)};
c6.prototype.get=function(a){return a?Z4(this.screens,a):null};
c6.prototype.info=function(a){Z5(this.I,a)};g.u(d6,g.R);g.k=d6.prototype;g.k.start=function(){!this.i&&isNaN(this.ib)&&this.eG()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.ib)||(g.Co(this.ib),this.ib=NaN)};
g.k.da=function(){this.stop();g.R.prototype.da.call(this)};
g.k.eG=function(){this.ib=NaN;this.i=g.Zp(W5(this.u,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.J},timeout:5E3,onSuccess:(0,g.B)(this.NJ,this),onError:(0,g.B)(this.MJ,this),onTimeout:(0,g.B)(this.OJ,this)})};
g.k.NJ=function(a,b){this.i=null;var c=b.screen||{};c.dialId=this.B;c.name=this.I;var d=-1;this.C&&c.shortLivedLoungeToken&&c.shortLivedLoungeToken.value&&c.shortLivedLoungeToken.refreshIntervalMs&&(c.screenIdType="shortLived",c.loungeToken=c.shortLivedLoungeToken.value,d=c.shortLivedLoungeToken.refreshIntervalMs);this.V("pairingComplete",new T4(c),d)};
g.k.MJ=function(a){this.i=null;a.status&&404==a.status?this.l>=wLa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=wLa[this.l],this.ib=g.Ao((0,g.B)(this.eG,this),a),this.l++):this.V("pairingFailed",Error("Server error "+a.status))};
g.k.OJ=function(){this.i=null;this.V("pairingFailed",Error("Server not responding"))};
var wLa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ta(f6,c6);g.k=f6.prototype;g.k.start=function(){e6(this)&&this.V("screenChange");!g.Ku("yt-remote-lounge-token-expiration")&&eKa(this);g.Co(this.i);this.i=g.Ao((0,g.B)(this.start,this),1E4)};
g.k.add=function(a,b){e6(this);bKa(this,a);g6(this,!1);this.V("screenChange");b(a);a.token||eKa(this)};
g.k.remove=function(a,b){var c=e6(this);dKa(this,a)&&(g6(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.k.Bv=function(a,b,c,d){var e=e6(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,g6(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.k.da=function(){g.Co(this.i);f6.Gd.da.call(this)};
g.k.xL=function(a){e6(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}g6(this,!b);b&&Z5(this.I,"Missed "+b+" lounge tokens.")};
g.k.wL=function(a){Z5(this.I,"Requesting lounge tokens failed: "+a)};g.u(i6,g.R);g.k=i6.prototype;g.k.start=function(){var a=parseInt(g.Ku("yt-remote-fast-check-period")||"0",10);(this.B=g.Sa()-144E5<a?0:a)?l6(this):(this.B=g.Sa()+3E5,g.Ju("yt-remote-fast-check-period",this.B),this.Lz())};
g.k.isEmpty=function(){return g.Pb(this.i)};
g.k.update=function(){h6("Updating availability on schedule.");var a=this.I(),b=g.Db(this.i,function(c,d){return c&&!!Z4(a,d)},this);
k6(this,b)};
g.k.da=function(){g.Co(this.u);this.u=NaN;this.l&&(this.l.abort(),this.l=null);g.R.prototype.da.call(this)};
g.k.Lz=function(){g.Co(this.u);this.u=NaN;this.l&&this.l.abort();var a=gKa(this);if(P4(a)){var b=W5(this.C,"/pairing/get_screen_availability");this.l=X5(this.C,b,{lounge_token:g.Kb(a).join(",")},(0,g.B)(this.WO,this,a),(0,g.B)(this.VO,this))}else k6(this,{}),l6(this)};
g.k.WO=function(a,b){this.l=null;var c=g.Kb(gKa(this));if(g.yb(c,g.Kb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;k6(this,d);l6(this)}else this.Id("Changing Screen set during request."),this.Lz()};
g.k.VO=function(a){this.Id("Screen availability failed: "+a);this.l=null;l6(this)};
g.k.Id=function(a){Z5("OnlineScreenService",a)};g.Ta(m6,c6);g.k=m6.prototype;g.k.start=function(){this.l.start();this.i.start();this.screens.length&&(this.V("screenChange"),this.i.isEmpty()||this.V("onlineScreenChange"))};
g.k.add=function(a,b,c){this.l.add(a,b,c)};
g.k.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.k.Bv=function(a,b,c,d){this.l.contains(a)?this.l.Bv(a,b,c,d):(a="Updating name of unknown screen: "+a.name,Z5(this.I,a),d(Error(a)))};
g.k.Ng=function(a){return a?this.screens:g.nb(this.screens,g.Ne(this.u,function(b){return!this.contains(b)},this))};
g.k.JB=function(){return g.Ne(this.Ng(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.KB=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new d6(this.B,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.Pi(l);e(n6(h,m),n)});
l.subscribe("pairingFailed",function(m){g.Pi(l);f(m)});
l.start();return(0,g.B)(l.stop,l)};
g.k.PJ=function(a,b,c,d){g.Zp(W5(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.B)(function(e,f){var h=new T4(f.screen||{});if(!h.name||kKa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);kKa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(n6(this,h))},this),
onError:(0,g.B)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.B)(function(){d(Error("pairing request timed out."))},this)})};
g.k.da=function(){g.Pi(this.l);g.Pi(this.i);m6.Gd.da.call(this)};
g.k.DL=function(){mKa(this);this.V("screenChange");this.i.update()};
m6.prototype.dispose=m6.prototype.dispose;g.Ta(p6,g.R);g.k=p6.prototype;g.k.getScreen=function(){return this.B};
g.k.dg=function(a){this.na()||(a&&r6(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.k.info=function(a){Z5(this.ia,a)};
g.k.LB=function(){return null};
g.k.Wz=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.B)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.B)(function(){r6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.da=function(){this.Wz("");p6.Gd.da.call(this)};g.u(s6,p6);g.k=s6.prototype;g.k.Vz=function(a){if(this.l){if(this.l==a)return;r6(this,"Overriding cast session with new session object");vKa(this);this.ca=!1;this.W="unknown";this.l.removeUpdateListener(this.Y);this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ea)}this.l=a;this.l.addUpdateListener(this.Y);this.l.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.ea);rKa(this,"getMdxSessionStatus")};
g.k.Vo=function(a){this.info("launchWithParams no-op for Cast: "+g.Qj(a))};
g.k.stop=function(){this.l?this.l.stop((0,g.B)(function(){this.dg()},this),(0,g.B)(function(){this.dg(Error("Failed to stop receiver app."))},this)):this.dg(Error("Stopping cast device without session."))};
g.k.Wz=function(){};
g.k.da=function(){this.info("disposeInternal");vKa(this);this.l&&(this.l.removeUpdateListener(this.Y),this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ea));this.l=null;p6.prototype.da.call(this)};
g.k.HP=function(a,b){if(!this.na())if(b){var c=m5(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Qj(c));switch(d){case "mdxSessionStatus":pKa(this,c);break;case "loungeToken":sKa(this,c);break;default:r6(this,"Unknown youtube message: "+d)}}else r6(this,"Unable to parse message.")}else r6(this,"No data in message.")};
g.k.KD=function(a,b,c,d){g.Co(this.L);this.L=0;jKa(this.u,this.i.label,a,this.i.friendlyName,(0,g.B)(function(e){e?b(e):0<=d?(r6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.L=g.Ao((0,g.B)(this.KD,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.LB=function(){return this.l};
g.k.QJ=function(a){this.na()||a||(r6(this,"Cast session died."),this.dg())};g.u(v6,p6);g.k=v6.prototype;g.k.Vz=function(a){this.l=a;this.l.addUpdateListener(this.ga)};
g.k.Vo=function(a){this.la=a;this.X()};
g.k.stop=function(){CKa(this);this.l?this.l.stop((0,g.B)(this.dg,this,null),(0,g.B)(this.dg,this,"Failed to stop DIAL device.")):this.dg()};
g.k.da=function(){CKa(this);this.l&&this.l.removeUpdateListener(this.ga);this.l=null;p6.prototype.da.call(this)};
g.k.RJ=function(a){this.na()||a||(r6(this,"DIAL session died."),this.C(),this.C=g.Ia,this.dg())};g.u(z6,p6);z6.prototype.stop=function(){this.dg()};
z6.prototype.Vz=function(){};
z6.prototype.Vo=function(){g.Co(this.l);this.l=NaN;var a=Z4(this.u.Ng(),this.i.label);a?q6(this,a):this.dg(Error("No such screen"))};
z6.prototype.da=function(){g.Co(this.l);this.l=NaN;p6.prototype.da.call(this)};g.u(A6,g.R);g.k=A6.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.L);this.W||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.B)(this.GO,this);c=new chrome.cast.ApiConfig(c,(0,g.B)(this.OF,this),f,d,e);c.customDialLaunchCallback=(0,g.B)(this.tN,this);chrome.cast.initialize(c,(0,g.B)(function(){this.na()||
(chrome.cast.addReceiverActionListener(this.I),YJa(),this.l.subscribe("onlineScreenChange",(0,g.B)(this.MB,this)),this.u=EKa(this),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.B)(function(h){this.Id("Failed to set initial custom receivers: "+g.Qj(h))},this)),this.V("yt-remote-cast2-availability-change",C6(this)),b(!0))},this),(0,g.B)(function(h){this.Id("Failed to initialize API: "+g.Qj(h));
b(!1)},this))};
g.k.qQ=function(a,b){B6("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)B6("Unsetting old screen status: "+this.i.i.friendlyName),D6(this,null)}if(a&&b){if(!this.i){c=Z4(this.l.Ng(),a);if(!c){B6("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){B6("setConnectedScreenStatus: Screen with id type to be short lived.");return}var d=DKa(this,c);d||(B6("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.u.push(d),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.B)(function(e){this.Id("Failed to set initial custom receivers: "+g.Qj(e))},this)));
B6("setConnectedScreenStatus: new active receiver: "+d.friendlyName);D6(this,new z6(this.l,d),!0)}this.i.Wz(b)}else B6("setConnectedScreenStatus: no screen.")};
g.k.rQ=function(a){this.na()?this.Id("Setting connection data on disposed cast v2"):this.i?this.i.Vo(a):this.Id("Setting connection data without a session")};
g.k.TJ=function(){this.na()?this.Id("Stopping session on disposed cast v2"):this.i?(this.i.stop(),D6(this,null)):B6("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.B)(this.OF,this),(0,g.B)(this.ZO,this))};
g.k.da=function(){this.l.unsubscribe("onlineScreenChange",(0,g.B)(this.MB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.I);var a=VJa,b=g.Ha("yt.mdx.remote.debug.handlers_");g.kb(b||[],a);g.Pi(this.i);g.R.prototype.da.call(this)};
g.k.Id=function(a){Z5("Controller",a)};
g.k.QF=function(a,b){this.i==a&&(b||D6(this,null),this.V("yt-remote-cast2-session-change",b))};
g.k.DO=function(a,b){if(!this.na())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),B6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)B6("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{B6("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.V("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:D6(this,
new z6(this.l,a));break;case chrome.cast.ReceiverType.DIAL:D6(this,new v6(this.l,a,this.C,this.B));break;case chrome.cast.ReceiverType.CAST:D6(this,new s6(this.l,a,this.B));break;default:this.Id("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.Id("Stopping receiver w/o session: "+a.friendlyName)}else this.Id("onReceiverAction_ called without receiver.")};
g.k.tN=function(a){if(this.na())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Id("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.Id("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return B6("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Id('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);D6(this,new v6(this.l,b,this.C,this.B))}b=this.i;b.L=a;b.L.appState==chrome.cast.DialAppState.RUNNING?(a=b.L.extraData||{},c=a.screenId||null,w6(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=zKa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.L.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.xo(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=AKa(b,c)):a=AKa(b,c)):a=y6(b);return a};
g.k.OF=function(a){if(!this.na()){B6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(b.receiverType==chrome.cast.ReceiverType.CAST)B6("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),D6(this,new s6(this.l,b,this.B),!0);else{this.Id("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.i.i,d=Z4(this.l.Ng(),c.label);d&&U4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(B6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Pi(this.i),this.i=new s6(this.l,b,this.B),this.i.subscribe("sessionScreen",(0,g.B)(this.QF,this,this.i)),this.i.Vo(null));this.i.Vz(a)}}};
g.k.SJ=function(){return this.i?this.i.LB():null};
g.k.ZO=function(a){this.na()||(this.Id("Failed to estabilish a session: "+g.Qj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&D6(this,null))};
g.k.GO=function(a){B6("Receiver availability updated: "+a);if(!this.na()){var b=C6(this);this.J=a==chrome.cast.ReceiverAvailability.AVAILABLE;C6(this)!=b&&this.V("yt-remote-cast2-availability-change",C6(this))}};
g.k.MB=function(){this.na()||(this.u=EKa(this),B6("Updating custom receivers: "+g.Qj(this.u)),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.B)(function(){this.Id("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",C6(this)))};
A6.prototype.setLaunchParams=A6.prototype.rQ;A6.prototype.setConnectedScreenStatus=A6.prototype.qQ;A6.prototype.stopSession=A6.prototype.TJ;A6.prototype.getCastSession=A6.prototype.SJ;A6.prototype.requestSession=A6.prototype.requestSession;A6.prototype.init=A6.prototype.init;A6.prototype.dispose=A6.prototype.dispose;var J6=[];g.k=O6.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";P6(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.i=a.trackData,this.Zi=a.hasPrevious,this.hasNext=a.hasNext,this.L=a.playerTime,this.J=a.playerTimeAt,this.C=a.seekableStart,this.l=a.seekableEnd,this.I=a.duration,this.W=a.loadedTime,this.B=a.liveIngestionTime,this.u=!isNaN(this.B))};
g.k.Mb=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.u?this.I+Q6(this):this.I};
g.k.clone=function(){return new O6(U6(this))};g.u(W6,g.R);g.k=W6.prototype;g.k.getState=function(){return this.Ma};
g.k.play=function(){Y6(this)?(this.i?this.i.play(null,g.Ia,c7(this,"play")):b7(this,"play"),a7(this,1,S6(X6(this))),this.V("remotePlayerChange")):Z6(this,this.play)};
g.k.pause=function(){Y6(this)?(this.i?this.i.pause(null,g.Ia,c7(this,"pause")):b7(this,"pause"),a7(this,2,S6(X6(this))),this.V("remotePlayerChange")):Z6(this,this.pause)};
g.k.seekTo=function(a){if(Y6(this)){if(this.i){var b=X6(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Mb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,c7(this,"seekTo",{newTime:a}))}else b7(this,"seekTo",{newTime:a});a7(this,3,a);this.V("remotePlayerChange")}else Z6(this,g.Qa(this.seekTo,a))};
g.k.stop=function(){if(Y6(this)){this.i?this.i.stop(null,g.Ia,c7(this,"stopVideo")):b7(this,"stopVideo");var a=X6(this);a.index=-1;a.videoId="";P6(a);$6(this,a);this.V("remotePlayerChange")}else Z6(this,this.stop)};
g.k.setVolume=function(a,b){if(Y6(this)){var c=X6(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.B)(function(){Z5("CP","set receiver volume: "+d)},this),(0,g.B)(function(){this.Id("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.B)(function(){Z5("CP","set receiver muted: "+b)},this),(0,g.B)(function(){this.Id("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);b7(this,"setVolume",e)}c.muted=b;c.volume=a;$6(this,c)}else Z6(this,g.Qa(this.setVolume,a,b))};
g.k.NB=function(a,b){if(Y6(this)){var c=X6(this),d={videoId:a};b&&(c.i={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Qj(b.style),g.Yb(d,c.i));b7(this,"setSubtitlesTrack",d);$6(this,c)}else Z6(this,g.Qa(this.NB,a,b))};
g.k.setAudioTrack=function(a,b){if(Y6(this)){var c=b.getLanguageInfo().getId();b7(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=X6(this);d.audioTrackId=c;$6(this,d)}else Z6(this,g.Qa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=X6(this);c=c||0;var m={videoId:a,currentIndex:c};T6(l,a,c);void 0!==b&&(R6(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Qj(h));b7(this,"setPlaylist",m);d||$6(this,l)};
g.k.Ou=function(a,b){if(Y6(this)){if(a&&b){var c=X6(this);T6(c,a,b);$6(this,c)}b7(this,"previous")}else Z6(this,g.Qa(this.Ou,a,b))};
g.k.nextVideo=function(a,b){if(Y6(this)){if(a&&b){var c=X6(this);T6(c,a,b);$6(this,c)}b7(this,"next")}else Z6(this,g.Qa(this.nextVideo,a,b))};
g.k.dD=function(){Y6(this)?b7(this,"dismissAutoplay"):Z6(this,this.dD)};
g.k.dispose=function(){if(3!=this.Ma){var a=this.Ma;this.Ma=3;this.V("proxyStateChange",a,this.Ma)}g.R.prototype.dispose.call(this)};
g.k.da=function(){QKa(this);this.u=null;this.B.clear();V6(this,null);g.R.prototype.da.call(this)};
g.k.Zz=function(a){if((a!=this.Ma||2==a)&&3!=this.Ma&&0!=a){var b=this.Ma;this.Ma=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.gb(b.i)&&(b.i=b.l,b.i.reverse(),b.l=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.AO=function(a,b){this.V(a,b)};
g.k.fN=function(a){if(!a)this.Cr(null),V6(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=X6(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)Z5("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,$6(this,b)}};
g.k.Cr=function(a){Z5("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.J);if(this.i=a)this.i.addUpdateListener(this.J),RKa(this),this.V("remotePlayerChange")};
g.k.eN=function(a){a?(RKa(this),this.V("remotePlayerChange")):this.Cr(null)};
g.k.qA=function(){b7(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.mN=function(){var a=NKa();a&&V6(this,a)};
g.k.Id=function(a){Z5("CP",a)};g.u(d7,g.R);g.k=d7.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.Hb.listId=c);this.Hb.videoId=d;this.Hb.index=h||0;this.Hb.state=3;R6(this.Hb,m);this.B="UNSUPPORTED";e7("Connecting with setPlaylist and params: "+g.Qj(l));this.i.connect({method:"setPlaylist",
params:g.Qj(l)},a,QIa())}else e7("Connecting without params"),this.i.connect({},a,QIa());TKa(this)};
g.k.cv=function(a){this.i.cv(a)};
g.k.dispose=function(){this.na()||(this.V("beforeDispose"),f7(this,3));g.R.prototype.dispose.call(this)};
g.k.da=function(){g7(this);i7(this);h7(this);g.Co(this.J);this.J=NaN;g.Co(this.L);this.L=NaN;this.u=null;g.cp(this.W);this.W.length=0;this.i.dispose();g.R.prototype.da.call(this);this.B=this.I=this.l=this.Hb=this.i=null};
g.k.rL=function(){this.xo(2)};
g.k.jN=function(){e7("Channel opened");this.ca&&(this.ca=!1,h7(this),this.Y=g.Ao((0,g.B)(function(){e7("Timing out waiting for a screen.");this.xo(1)},this),15E3));
UIa(TJa(this.i),this.ga)};
g.k.gN=function(){e7("Channel closed");isNaN(this.C)?d5(!0):d5();this.dispose()};
g.k.hN=function(a,b){d5();isNaN(this.Xq())?(b&&"shortLived"==this.ea&&this.V("browserChannelAuthError",a),e7("Channel error: "+a+" without reconnection"),this.dispose()):(this.ca=!0,e7("Channel error: "+a+" with reconnection in "+this.Xq()+" ms"),f7(this,2))};
g.k.iN=function(a){a.params?e7("Received: action="+a.action+", params="+g.Qj(a.params)):e7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=m5(a.params.devices);this.l=g.Qc(a,function(c){return new S4(c)});
a=!!g.cb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
WKa(this,a);break;case "loungeScreenDisconnected":g.lb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
WKa(this,!1);break;case "remoteConnected":var b=new S4(m5(a.params.device));g.cb(this.l,function(c){return b?c.id==b.id:!1})||AIa(this.l,b);
break;case "remoteDisconnected":b=new S4(m5(a.params.device));g.lb(this.l,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":YKa(this,a);break;case "nowPlaying":$Ka(this,a);break;case "onStateChange":ZKa(this,a);break;case "onAdStateChange":aLa(this,a);break;case "onVolumeChanged":bLa(this,a);break;case "onSubtitlesTrackChanged":XKa(this,a);break;case "nowAutoplaying":cLa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.I=a.params.videoId||null;this.V("autoplayUpNext",this.I);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.V("autoplayModeChange",this.B);"DISABLED"==this.B&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":dLa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:e7("Unrecognized action: "+a.action)}};
g.k.fQ=function(){if(this.u){var a=this.u;this.u=null;this.Hb.videoId!=a&&j7(this,"getNowPlaying")}};
g.k.nL=function(){var a=3;this.na()||(a=0,isNaN(this.Xq())?U5(this.i)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.xo=function(a){e7("Disconnecting with "+a);g7(this);this.V("beforeDisconnect",a);1==a&&d5();UJa(this.i,a);this.dispose()};
g.k.lL=function(){var a=this.Hb;this.u&&(a=this.Hb.clone(),T6(a,this.u,a.index));return U6(a)};
g.k.sQ=function(a){var b=new O6(a);b.videoId&&b.videoId!=this.Hb.videoId&&(this.u=b.videoId,g.Co(this.J),this.J=g.Ao((0,g.B)(this.fQ,this),5E3));var c=[];this.Hb.listId==b.listId&&this.Hb.videoId==b.videoId&&this.Hb.index==b.index||c.push("remoteQueueChange");this.Hb.playerState==b.playerState&&this.Hb.volume==b.volume&&this.Hb.muted==b.muted&&S6(this.Hb)==S6(b)&&g.Qj(this.Hb.i)==g.Qj(b.i)||c.push("remotePlayerChange");this.Hb.reset(a);g.Ab(c,function(d){this.V(d)},this)};
g.k.JD=function(){var a=this.i.I.id,b=g.cb(this.l,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Xq=function(){var a=this.i;return a.l.isActive()?a.l.l-g.Sa():NaN};
g.k.hL=function(){return this.B||"UNSUPPORTED"};
g.k.iL=function(){return this.I||""};
g.k.UJ=function(){if(!isNaN(this.Xq())){var a=this.i.l;a.i.pg();a.start()}};
g.k.oQ=function(a,b){j7(this,a,b);VKa(this)};
g.k.OB=function(){var a=g.Vq("SID","")||"",b=g.Vq("SAPISID","")||"",c=g.Vq("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.sf(g.Xe(a),2);b=g.sf(g.Xe(b),2);c=g.sf(g.Xe(c),2);return g.sf(g.Xe(a+","+b+","+c),2)};
d7.prototype.subscribe=d7.prototype.subscribe;d7.prototype.unsubscribeByKey=d7.prototype.Pf;d7.prototype.getProxyState=d7.prototype.nL;d7.prototype.disconnect=d7.prototype.xo;d7.prototype.getPlayerContextData=d7.prototype.lL;d7.prototype.setPlayerContextData=d7.prototype.sQ;d7.prototype.getOtherConnectedRemoteId=d7.prototype.JD;d7.prototype.getReconnectTimeout=d7.prototype.Xq;d7.prototype.getAutoplayMode=d7.prototype.hL;d7.prototype.getAutoplayVideoId=d7.prototype.iL;d7.prototype.reconnect=d7.prototype.UJ;
d7.prototype.sendMessage=d7.prototype.oQ;d7.prototype.getXsrfToken=d7.prototype.OB;g.u(k7,c6);g.k=k7.prototype;g.k.Ng=function(a){return this.Jf.$_gs(a)};
g.k.contains=function(a){return!!this.Jf.$_c(a)};
g.k.get=function(a){return this.Jf.$_g(a)};
g.k.start=function(){this.Jf.$_st()};
g.k.add=function(a,b,c){this.Jf.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Jf.$_r(a,b,c)};
g.k.Bv=function(a,b,c,d){this.Jf.$_un(a,b,c,d)};
g.k.da=function(){for(var a=0,b=this.i.length;a<b;++a)this.Jf.$_ubk(this.i[a]);this.i.length=0;this.Jf=null;c6.prototype.da.call(this)};
g.k.VJ=function(){this.V("screenChange")};
g.k.hO=function(){this.V("onlineScreenChange")};
m6.prototype.$_st=m6.prototype.start;m6.prototype.$_gspc=m6.prototype.PJ;m6.prototype.$_gsppc=m6.prototype.KB;m6.prototype.$_c=m6.prototype.contains;m6.prototype.$_g=m6.prototype.get;m6.prototype.$_a=m6.prototype.add;m6.prototype.$_un=m6.prototype.Bv;m6.prototype.$_r=m6.prototype.remove;m6.prototype.$_gs=m6.prototype.Ng;m6.prototype.$_gos=m6.prototype.JB;m6.prototype.$_s=m6.prototype.subscribe;m6.prototype.$_ubk=m6.prototype.Pf;var x7=null,D7=!1,l7=null,m7=null,C7=null,q7=[];g.u(E7,g.E);g.k=E7.prototype;g.k.da=function(){g.E.prototype.da.call(this);this.i.stop();this.u.stop();this.L.stop();this.Y();var a=this.xb;a.unsubscribe("proxyStateChange",this.LF,this);a.unsubscribe("remotePlayerChange",this.Ir,this);a.unsubscribe("remoteQueueChange",this.Mu,this);a.unsubscribe("previousNextChange",this.IF,this);a.unsubscribe("nowAutoplaying",this.DF,this);a.unsubscribe("autoplayDismissed",this.dF,this);this.xb=this.l=null};
g.k.PB=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.xb.Ma)if(F7(this)){if(!X6(this.xb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":X6(this.xb).Mb()?this.xb.pause():this.xb.play();break;case "control_play":this.xb.play();break;case "control_pause":this.xb.pause();break;case "control_seek":this.J.pg(c[0],c[1]);break;case "control_subtitles_set_track":G7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.G.getCurrentTime();H7(this,0===c?void 0:c);break;case "control_seek":H7(this,c[0]);break;case "control_subtitles_set_track":G7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.cN=function(a){this.L.pg(a)};
g.k.YQ=function(a){this.PB("control_subtitles_set_track",g.Pb(a)?null:a)};
g.k.aH=function(){var a=this.G.getOption("captions","track");g.Pb(a)||G7(this,a)};
g.k.Cb=function(a){this.l.Cb(a,this.G.getVideoData().lengthSeconds)};
g.k.QN=function(){g.Pb(this.B)||oLa(this,this.B);this.C=!1};
g.k.LF=function(a,b){this.u.stop();2===b&&this.VG()};
g.k.Ir=function(){if(F7(this)){this.i.stop();var a=X6(this.xb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.l.Pe=1;break;case 1082:case 1083:this.l.Pe=0;break;default:this.l.Pe=-1}switch(a.playerState){case 1081:case 1:this.ub(new g.DK(8));this.UG();break;case 1085:case 3:this.ub(new g.DK(9));break;case 1083:case 0:this.ub(new g.DK(2));this.J.stop();this.Cb(this.G.getVideoData().lengthSeconds);break;case 1084:this.ub(new g.DK(4));break;case 2:this.ub(new g.DK(4));this.Cb(S6(a));
break;case -1:this.ub(new g.DK(64));break;case -1E3:this.ub(new g.DK(128,{errorCode:"mdx.remoteerror",errorMessage:"\u9019\u90e8\u5f71\u7247\u4e0d\u63d0\u4f9b\u9060\u7aef\u64ad\u653e\u3002\u3000"}))}a=X6(this.xb).i;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,oLa(this,a));a=X6(this.xb);-1===a.volume||Math.round(this.G.getVolume())===a.volume&&this.G.isMuted()===a.muted||this.W.isActive()||this.xH()}else nLa(this)};
g.k.IF=function(){this.G.V("mdxpreviousnextchange")};
g.k.Mu=function(){F7(this)||nLa(this)};
g.k.DF=function(a){isNaN(a)||this.G.V("mdxnowautoplaying",a)};
g.k.dF=function(){this.G.V("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){F7(this)&&this.xb.setAudioTrack(this.G.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===X6(this.xb).playerState?H7(this,a):b&&this.xb.seekTo(a)};
g.k.xH=function(){var a=this;if(F7(this)){var b=X6(this.xb);this.events.Ib(this.X);b.muted?this.G.mute():this.G.unMute();this.G.setVolume(b.volume);this.X=this.events.N(this.G,"onVolumeChange",function(c){mLa(a,c)})}};
g.k.UG=function(){this.i.stop();if(!this.xb.na()){var a=X6(this.xb);a.Mb()&&this.ub(new g.DK(8));this.Cb(S6(a));this.i.start()}};
g.k.VG=function(){this.u.stop();this.i.stop();var a=this.xb.u.getReconnectTimeout();2==this.xb.Ma&&!isNaN(a)&&this.u.start()};
g.k.ub=function(a){this.u.stop();var b=this.I;if(!g.IK(b,a)){var c=g.W(a,2);c!==g.W(this.I,2)&&this.G.Hn(c);this.I=a;qLa(this.l,b,a)}};g.u(I7,g.X);I7.prototype.Gc=function(){this.i.show()};
I7.prototype.nb=function(){this.i.hide()};
I7.prototype.l=function(){g.jK("https://support.google.com/youtube/answer/7640706")};
I7.prototype.u=function(){R4("mdx-manual-pairing-popup-ok");this.nb()};g.u(J7,g.X);J7.prototype.Gc=function(){this.i.show()};
J7.prototype.nb=function(){this.i.hide()};
J7.prototype.l=function(){R4("mdx-privacy-popup-cancel");this.nb()};
J7.prototype.u=function(){R4("mdx-privacy-popup-confirm");this.nb()};g.u(K7,g.X);K7.prototype.l=function(a){pLa(this,a.state)};g.u(L7,g.qQ);L7.prototype.C=function(){var a=this.G.getOption("remote","receivers");a&&1<a.length&&!this.G.getOption("remote","quickCast")?(this.Pl=g.Bb(a,this.i,this),g.rQ(this,g.Qc(a,this.i)),a=this.G.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.fh(a),this.enable(!0)):this.enable(!1)};
L7.prototype.i=function(a){return a.key};
L7.prototype.Mh=function(a){return"cast-selector-receiver"===a?"\u6295\u653e\u2026":this.Pl[a].name};
L7.prototype.Xe=function(a){g.qQ.prototype.Xe.call(this,a);this.G.setOption("remote","currentReceiver",this.Pl[a]);this.eb.nb()};g.u(M7,g.GN);g.k=M7.prototype;
g.k.create=function(){var a=this.player.T(),b=g.YC(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.T(a.experiments,"mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:g.T(a.experiments,"enable_dial_short_lived_lounge_token"),enableCastLoungeToken:g.T(a.experiments,"enable_cast_short_lived_lounge_token")};hLa(b,a);this.subscriptions.push(g.Ho("yt-remote-before-disconnect",this.aN,this));this.subscriptions.push(g.Ho("yt-remote-connection-change",this.HO,this));this.subscriptions.push(g.Ho("yt-remote-receiver-availability-change",
this.KF,this));this.subscriptions.push(g.Ho("yt-remote-auto-connect",this.FO,this));this.subscriptions.push(g.Ho("yt-remote-receiver-resumed",this.EO,this));this.subscriptions.push(g.Ho("mdx-privacy-popup-confirm",this.VP,this));this.subscriptions.push(g.Ho("mdx-privacy-popup-cancel",this.UP,this));this.subscriptions.push(g.Ho("mdx-manual-pairing-popup-ok",this.jM,this));this.KF()};
g.k.load=function(){this.player.cancelPlayback();g.GN.prototype.load.call(this);this.kh=new E7(this,this.player,this.xb);var a=(a=lLa())?a.currentTime:0;var b=B7()?new W6(v7(),void 0):null;0==a&&b&&(a=S6(X6(b)));0!==a&&this.Cb(a);qLa(this,this.Pc,this.Pc);this.player.Aj(6)};
g.k.unload=function(){this.player.V("mdxautoplaycanceled");this.Zk=this.fi;g.Qi(this.kh,this.xb);this.xb=this.kh=null;g.GN.prototype.unload.call(this);this.player.Aj(5);N7(this)};
g.k.da=function(){g.Io(this.subscriptions);g.GN.prototype.da.call(this)};
g.k.qj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.kh.PB.apply(this.kh,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.Pe};
g.k.oL=function(){return this.loaded?this.kh.suggestion:null};
g.k.Zi=function(){return this.xb?X6(this.xb).Zi:!1};
g.k.hasNext=function(){return this.xb?X6(this.xb).hasNext:!1};
g.k.Cb=function(a,b){this.yE=a||0;this.player.V("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.yE};
g.k.getProgressState=function(){var a=X6(this.xb),b=this.player.getVideoData();return{allowSeeking:g.T(this.player.T().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Ne():!a.isAdPlaying()&&this.player.Ne(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.B+Q6(a):a.B,isAtLiveHead:1>=(a.u?a.l+Q6(a):a.l)-this.getCurrentTime(),loaded:a.W,seekableEnd:a.u?a.l+Q6(a):a.l,seekableStart:0<a.C?a.C+
Q6(a):a.C}};
g.k.nextVideo=function(){this.xb&&this.xb.nextVideo()};
g.k.Ou=function(){this.xb&&this.xb.Ou()};
g.k.aN=function(a){1===a&&(this.Az=this.xb?X6(this.xb):null)};
g.k.HO=function(){var a=B7()?new W6(v7(),void 0):null;if(a){var b=this.Zk;this.loaded&&this.unload();this.xb=a;this.Az=null;b.key!==this.fi.key&&(this.Zk=b,this.load())}else g.Pi(this.xb),this.xb=null,this.loaded&&(this.unload(),(a=this.Az)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,S6(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.KF=function(){var a=[this.fi],b=a.concat,c=iLa();K6()&&g.Ku("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Pl=b.call(a,c);a=w7()||this.fi;O7(this,a);this.player.ya("onMdxReceiversChange")};
g.k.FO=function(){var a=w7();O7(this,a)};
g.k.EO=function(){this.Zk=w7()};
g.k.VP=function(){this.Lr=!0;N7(this);D7=!1;x7&&z7(x7,1);x7=null};
g.k.UP=function(){this.Lr=!1;N7(this);O7(this,this.fi);this.Zk=this.fi;D7=!1;x7=null;this.player.playVideo()};
g.k.jM=function(){this.qu=!0;N7(this);g.Ju("yt-remote-manual-pairing-warning-shown",!0,2592E3);D7=!1;x7&&z7(x7,1);x7=null};
g.k.Ie=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Pl;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?M6():O7(this,b)),this.loaded?this.Zk:this.fi;case "quickCast":return 2===this.Pl.length&&"cast-selector-receiver"===this.Pl[1].key?(b&&M6(),!0):!1}};
g.k.qA=function(){this.xb.qA()};
g.k.wi=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.MN.remote=M7;})(_yt_player);
